import React from 'react'
import { TabelaGestantesImpressao } from './index'
export default {
  title: "Componentes/TabelaGestantesImpressao",
  component: TabelaGestantesImpressao,
};

const dataGestantes = [
  {
      "chave_id_gestacao": "ISABELA CRISTINA MARTINS FONSECA20011014_1",
      "municipio_id_sus": "111111",
      "equipe_ine": "0000278149",
      "equipe_nome": "ESF BARRINHA",
      "cidadao_nome": "ACRIMARIA ABRAO ABRAO",
      "cidadao_cpf_dt_nascimento": "34200324713",
      "gestacao_data_dpp": null,
      "gestacao_quadrimestre": "sem DUM",
      "gestacao_idade_gestacional_atual": null,
      "gestacao_idade_gestacional_primeiro_atendimento": null,
      "consulta_prenatal_ultima_data": "2023-10-16",
      "consultas_pre_natal_validas": null,
      "id_atendimento_odontologico": 3,
      "id_exame_hiv_sifilis": 5,
      "id_status_usuario": 11,
      "id_registro_parto": 2,
      "id_registro_aborto": 2,
      "acs_nome": "REALINA ORTEGA POVOA",
      "atualizacao_data": "2024-02-15",
      "criacao_data": "2024-01-09",
      "municipio_uf": "Impulsolândia - BR",
      "dt_registro_producao_mais_recente": "2024-01-04"
  },
  {
      "chave_id_gestacao": "ISLAYNE APARECIDA GOMES20021004_2",
      "municipio_id_sus": "111111",
      "equipe_ine": "0000278084",
      "equipe_nome": "PSF NOVA VICOSA",
      "cidadao_nome": "ADEILDA ABREU ABREU",
      "cidadao_cpf_dt_nascimento": "69345821421",
      "gestacao_data_dpp": null,
      "gestacao_quadrimestre": "sem DUM",
      "gestacao_idade_gestacional_atual": null,
      "gestacao_idade_gestacional_primeiro_atendimento": null,
      "consulta_prenatal_ultima_data": "2023-09-04",
      "consultas_pre_natal_validas": null,
      "id_atendimento_odontologico": 3,
      "id_exame_hiv_sifilis": 5,
      "id_status_usuario": 11,
      "id_registro_parto": 2,
      "id_registro_aborto": 2,
      "acs_nome": "CRISTOVAM NOLLA GOES",
      "atualizacao_data": "2024-02-15",
      "criacao_data": "2024-01-09",
      "municipio_uf": "Impulsolândia - BR",
      "dt_registro_producao_mais_recente": "2024-01-04"
  },
  {
      "chave_id_gestacao": "SANDY DAYANA NONATO19941205_1",
      "municipio_id_sus": "111111",
      "equipe_ine": "0000278041",
      "equipe_nome": "PSF AMORAS",
      "cidadao_nome": "ADEILDE ACRAS ACRAS",
      "cidadao_cpf_dt_nascimento": "29163539110",
      "gestacao_data_dpp": "2023-10-25",
      "gestacao_quadrimestre": "2023.Q3",
      "gestacao_idade_gestacional_atual": "58",
      "gestacao_idade_gestacional_primeiro_atendimento": "6",
      "consulta_prenatal_ultima_data": "2023-09-13",
      "consultas_pre_natal_validas": "9",
      "id_atendimento_odontologico": 2,
      "id_exame_hiv_sifilis": 4,
      "id_status_usuario": 9,
      "id_registro_parto": 1,
      "id_registro_aborto": 2,
      "acs_nome": "OTELITE EVANGELISTA CANTUARIA",
      "atualizacao_data": "2024-02-15",
      "criacao_data": "2024-01-09",
      "municipio_uf": "Impulsolândia - BR",
      "dt_registro_producao_mais_recente": "2024-01-04"
  },
  {
      "chave_id_gestacao": "PAMELA ESTEVAM ADAO20040712_1",
      "municipio_id_sus": "111111",
      "equipe_ine": "0001602721",
      "equipe_nome": "SAO JOSE CIDADE NOVA",
      "cidadao_nome": "ADELIA AKIYOSHI AKIYOSHI",
      "cidadao_cpf_dt_nascimento": "39499339431",
      "gestacao_data_dpp": "2024-03-16",
      "gestacao_quadrimestre": "2024.Q1",
      "gestacao_idade_gestacional_atual": "37",
      "gestacao_idade_gestacional_primeiro_atendimento": "7",
      "consulta_prenatal_ultima_data": "2023-12-19",
      "consultas_pre_natal_validas": "6",
      "id_atendimento_odontologico": 1,
      "id_exame_hiv_sifilis": 4,
      "id_status_usuario": 8,
      "id_registro_parto": 2,
      "id_registro_aborto": 2,
      "acs_nome": "ROMUALDO GARCIA MENDONCA",
      "atualizacao_data": "2024-02-15",
      "criacao_data": "2024-01-09",
      "municipio_uf": "Impulsolândia - BR",
      "dt_registro_producao_mais_recente": "2024-01-05"
  },
  {
      "chave_id_gestacao": "THAINARA DE SOUZA BARBOSA19990424_1",
      "municipio_id_sus": "111111",
      "equipe_ine": "0000278076",
      "equipe_nome": "PSF NOVA VICOSA POSSES",
      "cidadao_nome": "ADELICE ALAMINOS ALAMINOS",
      "cidadao_cpf_dt_nascimento": "13869184215",
      "gestacao_data_dpp": "2024-05-03",
      "gestacao_quadrimestre": "2024.Q2",
      "gestacao_idade_gestacional_atual": "30",
      "gestacao_idade_gestacional_primeiro_atendimento": "5",
      "consulta_prenatal_ultima_data": "2023-12-05",
      "consultas_pre_natal_validas": "4",
      "id_atendimento_odontologico": 1,
      "id_exame_hiv_sifilis": 4,
      "id_status_usuario": 8,
      "id_registro_parto": 2,
      "id_registro_aborto": 2,
      "acs_nome": "MAURILIO SALUSTINO NEPOMUCENO",
      "atualizacao_data": "2024-02-15",
      "criacao_data": "2024-01-09",
      "municipio_uf": "Impulsolândia - BR",
      "dt_registro_producao_mais_recente": "2024-01-09"
  },
  {
      "chave_id_gestacao": "RAYSSA ELLEN CASSIANO19940521_1",
      "municipio_id_sus": "111111",
      "equipe_ine": "0000278122",
      "equipe_nome": "PSF SANTO ANTONIO I",
      "cidadao_nome": "ADENILSA ALBANAN ALBANAN",
      "cidadao_cpf_dt_nascimento": "14366416532",
      "gestacao_data_dpp": "2023-10-30",
      "gestacao_quadrimestre": "2023.Q3",
      "gestacao_idade_gestacional_atual": "57",
      "gestacao_idade_gestacional_primeiro_atendimento": "19",
      "consulta_prenatal_ultima_data": "2023-09-19",
      "consultas_pre_natal_validas": "6",
      "id_atendimento_odontologico": 1,
      "id_exame_hiv_sifilis": 4,
      "id_status_usuario": 9,
      "id_registro_parto": 1,
      "id_registro_aborto": 2,
      "acs_nome": "ADENILSON PASSOS RESPLANDE",
      "atualizacao_data": "2024-02-15",
      "criacao_data": "2024-01-09",
      "municipio_uf": "Impulsolândia - BR",
      "dt_registro_producao_mais_recente": "2024-01-05"
  },
  {
      "chave_id_gestacao": "TALINE DOS REIS CUNHA19980926_1",
      "municipio_id_sus": "111111",
      "equipe_ine": "0001653660",
      "equipe_nome": "UNIDADE CENTRAL 2",
      "cidadao_nome": "ADENIRA ALBINO ALBINO",
      "cidadao_cpf_dt_nascimento": "92149011183",
      "gestacao_data_dpp": "2023-10-13",
      "gestacao_quadrimestre": "2023.Q3",
      "gestacao_idade_gestacional_atual": "59",
      "gestacao_idade_gestacional_primeiro_atendimento": "16",
      "consulta_prenatal_ultima_data": "2023-04-17",
      "consultas_pre_natal_validas": "1",
      "id_atendimento_odontologico": 2,
      "id_exame_hiv_sifilis": 4,
      "id_status_usuario": 9,
      "id_registro_parto": 1,
      "id_registro_aborto": 2,
      "acs_nome": "JESUS MARCHIOTTO CRUS",
      "atualizacao_data": "2024-02-15",
      "criacao_data": "2024-01-09",
      "municipio_uf": "Impulsolândia - BR",
      "dt_registro_producao_mais_recente": "2024-01-05"
  },
  {
      "chave_id_gestacao": "VANESSA SIMONINO DA SILVA19990528_1",
      "municipio_id_sus": "111111",
      "equipe_ine": "0000278076",
      "equipe_nome": "PSF NOVA VICOSA POSSES",
      "cidadao_nome": "ADIANA ALCANTARA ALCANTARA",
      "cidadao_cpf_dt_nascimento": "54267288378",
      "gestacao_data_dpp": "2024-01-26",
      "gestacao_quadrimestre": "2024.Q1",
      "gestacao_idade_gestacional_atual": "44",
      "gestacao_idade_gestacional_primeiro_atendimento": "25",
      "consulta_prenatal_ultima_data": "2024-01-05",
      "consultas_pre_natal_validas": "6",
      "id_atendimento_odontologico": 1,
      "id_exame_hiv_sifilis": 2,
      "id_status_usuario": 9,
      "id_registro_parto": 2,
      "id_registro_aborto": 2,
      "acs_nome": "ABGAIL FIDELIS LUCENA",
      "atualizacao_data": "2024-02-15",
      "criacao_data": "2024-01-09",
      "municipio_uf": "Impulsolândia - BR",
      "dt_registro_producao_mais_recente": "2024-01-09"
  },
  {
      "chave_id_gestacao": "VANESSA DORNELAS BRASIL20010723_1",
      "municipio_id_sus": "111111",
      "equipe_ine": "0001653660",
      "equipe_nome": "UNIDADE CENTRAL 2",
      "cidadao_nome": "ADIANEY ALELUIA ALELUIA",
      "cidadao_cpf_dt_nascimento": "43372095614",
      "gestacao_data_dpp": "2023-10-25",
      "gestacao_quadrimestre": "2023.Q3",
      "gestacao_idade_gestacional_atual": "58",
      "gestacao_idade_gestacional_primeiro_atendimento": "8",
      "consulta_prenatal_ultima_data": "2023-03-01",
      "consultas_pre_natal_validas": "1",
      "id_atendimento_odontologico": 2,
      "id_exame_hiv_sifilis": 3,
      "id_status_usuario": 9,
      "id_registro_parto": 2,
      "id_registro_aborto": 2,
      "acs_nome": "EMERECIANA SMAGNOTO PORT",
      "atualizacao_data": "2024-02-15",
      "criacao_data": "2024-01-09",
      "municipio_uf": "Impulsolândia - BR",
      "dt_registro_producao_mais_recente": "2024-01-05"
  },
  {
      "chave_id_gestacao": "KAILANE SIMONE DA SILVA20051224_1",
      "municipio_id_sus": "111111",
      "equipe_ine": "0000278149",
      "equipe_nome": "ESF BARRINHA",
      "cidadao_nome": "ADICELMA ALENCAR ALENCAR",
      "cidadao_cpf_dt_nascimento": "27923696812",
      "gestacao_data_dpp": "2024-03-14",
      "gestacao_quadrimestre": "2024.Q1",
      "gestacao_idade_gestacional_atual": "38",
      "gestacao_idade_gestacional_primeiro_atendimento": "7",
      "consulta_prenatal_ultima_data": "2023-12-28",
      "consultas_pre_natal_validas": "7",
      "id_atendimento_odontologico": 1,
      "id_exame_hiv_sifilis": 4,
      "id_status_usuario": 8,
      "id_registro_parto": 2,
      "id_registro_aborto": 2,
      "acs_nome": "ROBSON GABALDI MATTOS",
      "atualizacao_data": "2024-02-15",
      "criacao_data": "2024-01-09",
      "municipio_uf": "Impulsolândia - BR",
      "dt_registro_producao_mais_recente": "2024-01-04"
  },
  {
      "chave_id_gestacao": "GABRIELLY VITORIA GOMES VALENTE20080628_1",
      "municipio_id_sus": "111111",
      "equipe_ine": "0000278076",
      "equipe_nome": "PSF NOVA VICOSA POSSES",
      "cidadao_nome": "ADRIELE ALVAREZ ALVAREZ",
      "cidadao_cpf_dt_nascimento": "50842918581",
      "gestacao_data_dpp": "2023-10-25",
      "gestacao_quadrimestre": "2023.Q3",
      "gestacao_idade_gestacional_atual": "58",
      "gestacao_idade_gestacional_primeiro_atendimento": "9",
      "consulta_prenatal_ultima_data": "2023-07-11",
      "consultas_pre_natal_validas": "4",
      "id_atendimento_odontologico": 1,
      "id_exame_hiv_sifilis": 4,
      "id_status_usuario": 9,
      "id_registro_parto": 1,
      "id_registro_aborto": 2,
      "acs_nome": "DALMIR OHTA GONTIJO",
      "atualizacao_data": "2024-02-15",
      "criacao_data": "2024-01-09",
      "municipio_uf": "Impulsolândia - BR",
      "dt_registro_producao_mais_recente": "2024-01-09"
  },
  {
      "chave_id_gestacao": "TAYNA RODRIGUES MOREIRA19950701_2",
      "municipio_id_sus": "111111",
      "equipe_ine": "0000278092",
      "equipe_nome": "PSF SILVESTRE",
      "cidadao_nome": "ADRIELLY ALVIM ALVIM",
      "cidadao_cpf_dt_nascimento": "83191439949",
      "gestacao_data_dpp": null,
      "gestacao_quadrimestre": "sem DUM",
      "gestacao_idade_gestacional_atual": null,
      "gestacao_idade_gestacional_primeiro_atendimento": null,
      "consulta_prenatal_ultima_data": "2023-09-15",
      "consultas_pre_natal_validas": null,
      "id_atendimento_odontologico": 3,
      "id_exame_hiv_sifilis": 5,
      "id_status_usuario": 11,
      "id_registro_parto": 2,
      "id_registro_aborto": 2,
      "acs_nome": "RAIMUNDA ABRAO ABADIA",
      "atualizacao_data": "2024-02-15",
      "criacao_data": "2024-01-09",
      "municipio_uf": "Impulsolândia - BR",
      "dt_registro_producao_mais_recente": "2024-01-02"
  },
  {
      "chave_id_gestacao": "RENATA SOARES SILVA20000229_1",
      "municipio_id_sus": "111111",
      "equipe_ine": "0000278149",
      "equipe_nome": "ESF BARRINHA",
      "cidadao_nome": "ADRIENE AMANCIO AMANCIO",
      "cidadao_cpf_dt_nascimento": "67383479916",
      "gestacao_data_dpp": "2024-06-06",
      "gestacao_quadrimestre": "2024.Q2",
      "gestacao_idade_gestacional_atual": "26",
      "gestacao_idade_gestacional_primeiro_atendimento": "8",
      "consulta_prenatal_ultima_data": "2023-12-28",
      "consultas_pre_natal_validas": "3",
      "id_atendimento_odontologico": 2,
      "id_exame_hiv_sifilis": 4,
      "id_status_usuario": 8,
      "id_registro_parto": 2,
      "id_registro_aborto": 2,
      "acs_nome": "ADEILSON FOGACA MALAQUIAS",
      "atualizacao_data": "2024-02-15",
      "criacao_data": "2024-01-09",
      "municipio_uf": "Impulsolândia - BR",
      "dt_registro_producao_mais_recente": "2024-01-04"
  },
  {
      "chave_id_gestacao": "RAIZA FERNANDA CANDIDO20040112_1",
      "municipio_id_sus": "111111",
      "equipe_ine": "0000278149",
      "equipe_nome": "ESF BARRINHA",
      "cidadao_nome": "AGLAUPE AMARO AMARO",
      "cidadao_cpf_dt_nascimento": "83552083057",
      "gestacao_data_dpp": "2024-03-14",
      "gestacao_quadrimestre": "2024.Q1",
      "gestacao_idade_gestacional_atual": "38",
      "gestacao_idade_gestacional_primeiro_atendimento": "7",
      "consulta_prenatal_ultima_data": "2024-01-04",
      "consultas_pre_natal_validas": "10",
      "id_atendimento_odontologico": 1,
      "id_exame_hiv_sifilis": 4,
      "id_status_usuario": 8,
      "id_registro_parto": 2,
      "id_registro_aborto": 2,
      "acs_nome": "AJOANI GODEZ VIDIGAL",
      "atualizacao_data": "2024-02-15",
      "criacao_data": "2024-01-09",
      "municipio_uf": "Impulsolândia - BR",
      "dt_registro_producao_mais_recente": "2024-01-04"
  },
  {
      "chave_id_gestacao": "PATRICIA DA SILVA DO CARMO19961219_1",
      "municipio_id_sus": "111111",
      "equipe_ine": "0000278041",
      "equipe_nome": "PSF AMORAS",
      "cidadao_nome": "AIMARA AMERICO AMERICO",
      "cidadao_cpf_dt_nascimento": "78184034021",
      "gestacao_data_dpp": "2023-11-10",
      "gestacao_quadrimestre": "2023.Q3",
      "gestacao_idade_gestacional_atual": "55",
      "gestacao_idade_gestacional_primeiro_atendimento": "8",
      "consulta_prenatal_ultima_data": "2023-10-19",
      "consultas_pre_natal_validas": "12",
      "id_atendimento_odontologico": 1,
      "id_exame_hiv_sifilis": 4,
      "id_status_usuario": 9,
      "id_registro_parto": 2,
      "id_registro_aborto": 2,
      "acs_nome": "GENARO NOGUEIRA BARRETOS",
      "atualizacao_data": "2024-02-15",
      "criacao_data": "2024-01-09",
      "municipio_uf": "Impulsolândia - BR",
      "dt_registro_producao_mais_recente": "2024-01-04"
  },
  {
      "chave_id_gestacao": "THAIS VITORIA HONORATO JUSTINO20020404_1",
      "municipio_id_sus": "111111",
      "equipe_ine": "0000278181",
      "equipe_nome": "PSF BOM JESUS",
      "cidadao_nome": "AKEMIRIS AMORIM AMORIM",
      "cidadao_cpf_dt_nascimento": "65756038821",
      "gestacao_data_dpp": "2024-05-13",
      "gestacao_quadrimestre": "2024.Q2",
      "gestacao_idade_gestacional_atual": "29",
      "gestacao_idade_gestacional_primeiro_atendimento": "22",
      "consulta_prenatal_ultima_data": "2023-12-26",
      "consultas_pre_natal_validas": "1",
      "id_atendimento_odontologico": 2,
      "id_exame_hiv_sifilis": 4,
      "id_status_usuario": 8,
      "id_registro_parto": 1,
      "id_registro_aborto": 2,
      "acs_nome": "IZALTINA LIECNIENSKI CARLOS",
      "atualizacao_data": "2024-02-15",
      "criacao_data": "2024-01-09",
      "municipio_uf": "Impulsolândia - BR",
      "dt_registro_producao_mais_recente": "2024-01-03"
  },
  {
      "chave_id_gestacao": "THALIA ANDRIELE GOMES CRISPIM19970922_1",
      "municipio_id_sus": "111111",
      "equipe_ine": "0000278076",
      "equipe_nome": "PSF NOVA VICOSA POSSES",
      "cidadao_nome": "ALAEIDE AMPARO AMPARO",
      "cidadao_cpf_dt_nascimento": "22384383251",
      "gestacao_data_dpp": "2024-05-01",
      "gestacao_quadrimestre": "2024.Q2",
      "gestacao_idade_gestacional_atual": "31",
      "gestacao_idade_gestacional_primeiro_atendimento": "4",
      "consulta_prenatal_ultima_data": "2023-11-21",
      "consultas_pre_natal_validas": "7",
      "id_atendimento_odontologico": 1,
      "id_exame_hiv_sifilis": 4,
      "id_status_usuario": 8,
      "id_registro_parto": 2,
      "id_registro_aborto": 2,
      "acs_nome": "WALDEMIR TORREABLA CARVALHO",
      "atualizacao_data": "2024-02-15",
      "criacao_data": "2024-01-09",
      "municipio_uf": "Impulsolândia - BR",
      "dt_registro_producao_mais_recente": "2024-01-09"
  },
  {
      "chave_id_gestacao": "VITORIA DE FATIMA FORTUNATO20010513_1",
      "municipio_id_sus": "111111",
      "equipe_ine": "0000278122",
      "equipe_nome": "PSF SANTO ANTONIO I",
      "cidadao_nome": "ALAIANE ANANIAS ANANIAS",
      "cidadao_cpf_dt_nascimento": "77797183350",
      "gestacao_data_dpp": "2024-06-15",
      "gestacao_quadrimestre": "2024.Q2",
      "gestacao_idade_gestacional_atual": "24",
      "gestacao_idade_gestacional_primeiro_atendimento": "2",
      "consulta_prenatal_ultima_data": "2023-12-14",
      "consultas_pre_natal_validas": "3",
      "id_atendimento_odontologico": 1,
      "id_exame_hiv_sifilis": 4,
      "id_status_usuario": 8,
      "id_registro_parto": 2,
      "id_registro_aborto": 2,
      "acs_nome": "VITAL MARTINEZ TRANQUEIRA",
      "atualizacao_data": "2024-02-15",
      "criacao_data": "2024-01-09",
      "municipio_uf": "Impulsolândia - BR",
      "dt_registro_producao_mais_recente": "2024-01-05"
  },
  {
      "chave_id_gestacao": "LAYSA CRISTINA RAMOS20030303_1",
      "municipio_id_sus": "111111",
      "equipe_ine": "0000278092",
      "equipe_nome": "PSF SILVESTRE",
      "cidadao_nome": "ALAIDE ANCELMO ANCELMO",
      "cidadao_cpf_dt_nascimento": "72644715990",
      "gestacao_data_dpp": "2023-11-22",
      "gestacao_quadrimestre": "2023.Q3",
      "gestacao_idade_gestacional_atual": "54",
      "gestacao_idade_gestacional_primeiro_atendimento": "8",
      "consulta_prenatal_ultima_data": "2023-11-09",
      "consultas_pre_natal_validas": "8",
      "id_atendimento_odontologico": 1,
      "id_exame_hiv_sifilis": 4,
      "id_status_usuario": 9,
      "id_registro_parto": 2,
      "id_registro_aborto": 2,
      "acs_nome": "ANIELLE CAFE MALAQUIAS",
      "atualizacao_data": "2024-02-15",
      "criacao_data": "2024-01-09",
      "municipio_uf": "Impulsolândia - BR",
      "dt_registro_producao_mais_recente": "2024-01-02"
  },
  {
      "chave_id_gestacao": "IASMYN TEIXEIRA DIAS PEREIRA20090311_1",
      "municipio_id_sus": "111111",
      "equipe_ine": "0000278084",
      "equipe_nome": "PSF NOVA VICOSA",
      "cidadao_nome": "ALAÍDE ANDRADE ANDRADE",
      "cidadao_cpf_dt_nascimento": "70101996935",
      "gestacao_data_dpp": "2023-10-19",
      "gestacao_quadrimestre": "2023.Q3",
      "gestacao_idade_gestacional_atual": "59",
      "gestacao_idade_gestacional_primeiro_atendimento": "14",
      "consulta_prenatal_ultima_data": "2023-04-17",
      "consultas_pre_natal_validas": "2",
      "id_atendimento_odontologico": 2,
      "id_exame_hiv_sifilis": 4,
      "id_status_usuario": 9,
      "id_registro_parto": 1,
      "id_registro_aborto": 2,
      "acs_nome": "BIBIANA MARCIANO TAVARES",
      "atualizacao_data": "2024-02-15",
      "criacao_data": "2024-01-09",
      "municipio_uf": "Impulsolândia - BR",
      "dt_registro_producao_mais_recente": "2024-01-04"
  },
  {
      "chave_id_gestacao": "NATANIANI DE OLIVEIRA SILVA20031126_1",
      "municipio_id_sus": "111111",
      "equipe_ine": "0000278084",
      "equipe_nome": "PSF NOVA VICOSA",
      "cidadao_nome": "ALAISA ANGELONFERREIRA ANGELONFERREIRA",
      "cidadao_cpf_dt_nascimento": "44159566168",
      "gestacao_data_dpp": "2024-04-24",
      "gestacao_quadrimestre": "2024.Q1",
      "gestacao_idade_gestacional_atual": "32",
      "gestacao_idade_gestacional_primeiro_atendimento": "8",
      "consulta_prenatal_ultima_data": "2023-11-07",
      "consultas_pre_natal_validas": "5",
      "id_atendimento_odontologico": 1,
      "id_exame_hiv_sifilis": 4,
      "id_status_usuario": 8,
      "id_registro_parto": 2,
      "id_registro_aborto": 2,
      "acs_nome": "CLEONISIA FAGUNDES LEANDRO",
      "atualizacao_data": "2024-02-15",
      "criacao_data": "2024-01-09",
      "municipio_uf": "Impulsolândia - BR",
      "dt_registro_producao_mais_recente": "2024-01-04"
  },
  {
      "chave_id_gestacao": "GLAUCIENE AUGUSTO COELHO19920801_1",
      "municipio_id_sus": "111111",
      "equipe_ine": "0001602721",
      "equipe_nome": "SAO JOSE CIDADE NOVA",
      "cidadao_nome": "ALAIS ANGELO ANGELO",
      "cidadao_cpf_dt_nascimento": "81761511931",
      "gestacao_data_dpp": "2023-12-03",
      "gestacao_quadrimestre": "2023.Q3",
      "gestacao_idade_gestacional_atual": "52",
      "gestacao_idade_gestacional_primeiro_atendimento": "10",
      "consulta_prenatal_ultima_data": "2023-11-09",
      "consultas_pre_natal_validas": "12",
      "id_atendimento_odontologico": 1,
      "id_exame_hiv_sifilis": 4,
      "id_status_usuario": 9,
      "id_registro_parto": 1,
      "id_registro_aborto": 2,
      "acs_nome": "SILVANIA BRITIS CHAVEIRO",
      "atualizacao_data": "2024-02-15",
      "criacao_data": "2024-01-09",
      "municipio_uf": "Impulsolândia - BR",
      "dt_registro_producao_mais_recente": "2024-01-05"
  },
  {
      "chave_id_gestacao": "JULIA RODRIGUES DE FREITAS19910325_1",
      "municipio_id_sus": "111111",
      "equipe_ine": "0000278130",
      "equipe_nome": "PSF SAO SEBASTIAO",
      "cidadao_nome": "ALANA ANSELMO ANSELMO",
      "cidadao_cpf_dt_nascimento": "70084505552",
      "gestacao_data_dpp": "2024-05-30",
      "gestacao_quadrimestre": "2024.Q2",
      "gestacao_idade_gestacional_atual": "27",
      "gestacao_idade_gestacional_primeiro_atendimento": "11",
      "consulta_prenatal_ultima_data": "2023-12-28",
      "consultas_pre_natal_validas": "3",
      "id_atendimento_odontologico": 2,
      "id_exame_hiv_sifilis": 4,
      "id_status_usuario": 8,
      "id_registro_parto": 2,
      "id_registro_aborto": 2,
      "acs_nome": "CLAUDIA VICENTE CUNDE",
      "atualizacao_data": "2024-02-15",
      "criacao_data": "2024-01-09",
      "municipio_uf": "Impulsolândia - BR",
      "dt_registro_producao_mais_recente": "2024-01-05"
  },
]
const colunasGestantes=[
  {
    align: 'left',
    field: 'cidadao_nome',
    headerAlign: 'center',
    headerName: 'NOME',
    width: 320,
    sortable : false
  },
  {
    align: 'center',
    field: 'cidadao_cpf_dt_nascimento',
    headerName: 'CPF / DATA DE NASCIMENTO',
    width: 140,
    sortable : false
  },
  {
    align: 'center',
    field: 'gestacao_data_dpp',
    headerAlign: 'center',
    headerName: 'DPP + 14 DIAS',
    width: 100,
    sortable : false,
  },
  {
    align: 'center',
    field: 'gestacao_idade_gestacional_primeiro_atendimento',
    headerAlign: 'center',
    headerName: 'IG (1ª CONSULTA)',
    width: 90,
    sortable : false,

  },
  {
    align: 'center',
    field: 'gestacao_idade_gestacional_atual',
    headerAlign: 'center',
    headerName: 'IG ATUAL',
    width: 65,
    sortable : false,
  },
  {
    align: 'center',
    field: 'consultas_pre_natal_validas',
    headerAlign: 'center',
    headerName: 'TOTAL DE CONSULTAS VALIDAS',
    width: 100,
    sortable : false,
  },
  {
    align: 'center',
    field: 'consulta_prenatal_ultima_data',
    headerAlign: 'center',
    headerName: 'ÚLTIMA CONSULTA',
    width: 115,
    sortable : false,
  },
  {
      align: 'center',
      field: 'id_exame_hiv_sifilis',
      headerAlign: 'center',
      headerName: 'EXAME DE HIV/SÍFILIS',
      width: 150,
      sortable : false,
  },
  {
      align: 'center',
      field: 'id_atendimento_odontologico',
      headerAlign: 'center',
      headerName: 'ATENDIMENTO ODONTOLÓGICO',
      width: 120,
      sortable : false,
  },
  {
      align: 'center',
      field: 'acs_nome',
      headerAlign: 'center',
      headerName: 'PROFISSIONAL RESPONSÁVEL',
      width: 300,
      sortable : false
  },
    
]

const Template = (args) => <TabelaGestantesImpressao {...args}/>

export const TabelaGestantes = Template.bind({});

TabelaGestantes.args={
  data : dataGestantes,
  colunas : colunasGestantes,
}