export const completarMargens = (data)=>{
    const ALTURA_FOLHA_A4_PAISAGEM_PX = 970
    const ALTURA_CABECALHO_PAGINA = 82
    const ALTURA_TITULO_TABELA = 36
    const ALTURA_CABECALHO_TABELA = 34
    const ALTURA_LINHA_CITOPATOLOGICO = 38
    const HEADER_GERAL_FIXO = ALTURA_CABECALHO_PAGINA + ALTURA_TITULO_TABELA + ALTURA_CABECALHO_TABELA
    const MARGEM = ALTURA_FOLHA_A4_PAISAGEM_PX - (HEADER_GERAL_FIXO + (data.length * ALTURA_LINHA_CITOPATOLOGICO) )
    return MARGEM < 0 ? 0 : MARGEM
  }