export const completarMargens = (data)=>{
    const ALTURA_FOLHA_A4_PAISAGEM_PX = 793
    const ALTURA_CABECALHO_PAGINA = 82
    const ALTURA_TITULO_TABELA = 27
    const ALTURA_CABECALHO_TABELA = 31
    const ALTURA_LINHA_CITOPATOLOGICO = 27
    const HEADER_GERAL_FIXO = ALTURA_CABECALHO_PAGINA + ALTURA_TITULO_TABELA + ALTURA_CABECALHO_TABELA
    const MARGEM = ALTURA_FOLHA_A4_PAISAGEM_PX - (HEADER_GERAL_FIXO + (data.length * ALTURA_LINHA_CITOPATOLOGICO) )
    return MARGEM
}