import React from 'react'
import { TabelaVacinacaoImpressao } from './index'
export default {
  title: "Componentes/TabelaVacinacaoImpressao",
  component: TabelaVacinacaoImpressao,
};

const status_usuario_descricao = {
  "data" : [
  {
    "id_status_usuario" : 0,
    "status_usuario_descricao" : "Sem dados",
    "atualizacao_data" : "2023-05-02T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 1,
    "status_usuario_descricao" : "Com consulta e aferição de PA em dia",
    "atualizacao_data" : "2023-05-02T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 2,
    "status_usuario_descricao" : "Sem consulta e aferição de PA em dia",
    "atualizacao_data" : "2023-05-02T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 3,
    "status_usuario_descricao" : "Sem consulta em dia",
    "atualizacao_data" : "2023-05-02T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 4,
    "status_usuario_descricao" : "Sem aferição de PA em dia",
    "atualizacao_data" : "2023-05-02T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 5,
    "status_usuario_descricao" : "Com consulta e solicitação de hemoglobina em dia",
    "atualizacao_data" : "2023-05-02T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 6,
    "status_usuario_descricao" : "Sem consulta e solicitação de hemoglobina em dia",
    "atualizacao_data" : "2023-05-02T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 7,
    "status_usuario_descricao" : "Sem solicitação de hemoglobina em dia",
    "atualizacao_data" : "2023-05-02T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 8,
    "status_usuario_descricao" : "Encerradas por DPP + 14 dias",
    "atualizacao_data" : "2023-05-02T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 9,
    "status_usuario_descricao" : "Encerradas por parto ou aborto",
    "atualizacao_data" : "2023-05-15T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 10,
    "status_usuario_descricao" : "Ativas",
    "atualizacao_data" : "2023-05-15T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 11,
    "status_usuario_descricao" : "Gestantes inválidas",
    "atualizacao_data" : "2023-05-15T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 12,
    "status_usuario_descricao" : "Coleta em dia",
    "atualizacao_data" : "2023-07-03T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 13,
    "status_usuario_descricao" : "Nunca realizou coleta",
    "atualizacao_data" : "2023-07-03T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 14,
    "status_usuario_descricao" : "Coleta com menos de 25 anos",
    "atualizacao_data" : "2023-07-03T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 15,
    "status_usuario_descricao" : "Vence no final do quadrimestre",
    "atualizacao_data" : "2023-07-03T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 16,
    "status_usuario_descricao" : "Coleta vencida",
    "atualizacao_data" : "2023-07-03T03:00:00.000Z"
  }
]
}
const dataVacinacao = [
  {
      "municipio_id_sus": "431370",
      "municipio_uf": "Palmeira das Missões - RS",
      "cidadao_nome": "AA ALMEIDA",
      "cidadao_nome_responsavel": "RESPONSÁVEL NÃO IDENTIFICADO",
      "cidadao_cpf_dt_nascimento": "2023-07-27",
      "cidadao_idade_meses": 5,
      "quadrimestre_completa_1_ano": "2024.Q2",
      "id_status_quadrimestre": 2,
      "data_ou_prazo_1dose_polio": "2023-09-27",
      "data_ou_prazo_2dose_polio": "2023-11-27",
      "data_ou_prazo_3dose_polio": "2024-01-27",
      "id_status_polio": 30,
      "id_cor_1dose_polio": 3,
      "id_cor_2dose_polio": 3,
      "id_cor_3dose_polio": 1,
      "data_ou_prazo_1dose_penta": "2023-09-27",
      "data_ou_prazo_2dose_penta": "2023-11-27",
      "data_ou_prazo_3dose_penta": "2024-01-27",
      "id_status_penta": 3,
      "id_cor_1dose_penta": 3,
      "id_cor_2dose_penta": 3,
      "id_cor_3dose_penta": 1,
      "acs_nome": "SEM VISITA OU CADASTRO",
      "equipe_ine": "-",
      "equipe_nome": "SEM EQUIPE",
      "criacao_data": "2024-01-22",
      "atualizacao_data": "2024-01-22",
      "dt_registro_producao_mais_recente": "2024-01-19"
  },
  {
      "municipio_id_sus": "431370",
      "municipio_uf": "Palmeira das Missões - RS",
      "cidadao_nome": "AARON LIMA ARTILES",
      "cidadao_nome_responsavel": "RESPONSÁVEL NÃO IDENTIFICADO",
      "cidadao_cpf_dt_nascimento": "07158145085",
      "cidadao_idade_meses": 5,
      "quadrimestre_completa_1_ano": "2024.Q2",
      "id_status_quadrimestre": 2,
      "data_ou_prazo_1dose_polio": "2023-09-26",
      "data_ou_prazo_2dose_polio": "2023-11-27",
      "data_ou_prazo_3dose_polio": "2024-01-27",
      "id_status_polio": 20,
      "id_cor_1dose_polio": 2,
      "id_cor_2dose_polio": 2,
      "id_cor_3dose_polio": 1,
      "data_ou_prazo_1dose_penta": "2023-09-26",
      "data_ou_prazo_2dose_penta": "2023-11-27",
      "data_ou_prazo_3dose_penta": "2024-01-27",
      "id_status_penta": 2,
      "id_cor_1dose_penta": 2,
      "id_cor_2dose_penta": 2,
      "id_cor_3dose_penta": 1,
      "acs_nome": "SEM VISITA OU CADASTRO",
      "equipe_ine": "0000428388",
      "equipe_nome": "ESF IV - CENTRO SOCIAL URBANO",
      "criacao_data": "2024-01-22",
      "atualizacao_data": "2024-01-22",
      "dt_registro_producao_mais_recente": "2024-01-16"
  },
  {
      "municipio_id_sus": "431370",
      "municipio_uf": "Palmeira das Missões - RS",
      "cidadao_nome": "ABIMAEL DUARTE PEREIRA",
      "cidadao_nome_responsavel": "RESPONSÁVEL NÃO IDENTIFICADO",
      "cidadao_cpf_dt_nascimento": "01627163034",
      "cidadao_idade_meses": 1,
      "quadrimestre_completa_1_ano": "2024.Q3",
      "id_status_quadrimestre": 3,
      "data_ou_prazo_1dose_polio": "2024-02-11",
      "data_ou_prazo_2dose_polio": "2024-04-11",
      "data_ou_prazo_3dose_polio": "2024-06-11",
      "id_status_polio": 40,
      "id_cor_1dose_polio": 1,
      "id_cor_2dose_polio": 1,
      "id_cor_3dose_polio": 1,
      "data_ou_prazo_1dose_penta": "2024-02-11",
      "data_ou_prazo_2dose_penta": "2024-04-11",
      "data_ou_prazo_3dose_penta": "2024-06-11",
      "id_status_penta": 4,
      "id_cor_1dose_penta": 1,
      "id_cor_2dose_penta": 1,
      "id_cor_3dose_penta": 1,
      "acs_nome": "SEM VISITA OU CADASTRO",
      "equipe_ine": "0000428361",
      "equipe_nome": "ESV III - CENTRO SOCIAL URBANO",
      "criacao_data": "2024-01-22",
      "atualizacao_data": "2024-01-22",
      "dt_registro_producao_mais_recente": "2024-01-16"
  },
  {
      "municipio_id_sus": "431370",
      "municipio_uf": "Palmeira das Missões - RS",
      "cidadao_nome": "AGATHA DE LIMA ESTULANO",
      "cidadao_nome_responsavel": "RESPONSÁVEL NÃO IDENTIFICADO",
      "cidadao_cpf_dt_nascimento": "07107154044",
      "cidadao_idade_meses": 9,
      "quadrimestre_completa_1_ano": "2024.Q1",
      "id_status_quadrimestre": 1,
      "data_ou_prazo_1dose_polio": "2023-06-20",
      "data_ou_prazo_2dose_polio": "2023-08-22",
      "data_ou_prazo_3dose_polio": "2023-10-23",
      "id_status_polio": 10,
      "id_cor_1dose_polio": 2,
      "id_cor_2dose_polio": 2,
      "id_cor_3dose_polio": 2,
      "data_ou_prazo_1dose_penta": "2023-06-20",
      "data_ou_prazo_2dose_penta": "2023-08-22",
      "data_ou_prazo_3dose_penta": "2023-10-23",
      "id_status_penta": 1,
      "id_cor_1dose_penta": 2,
      "id_cor_2dose_penta": 2,
      "id_cor_3dose_penta": 2,
      "acs_nome": "SEM VISITA OU CADASTRO",
      "equipe_ine": "0000428388",
      "equipe_nome": "ESF IV - CENTRO SOCIAL URBANO",
      "criacao_data": "2024-01-22",
      "atualizacao_data": "2024-01-22",
      "dt_registro_producao_mais_recente": "2024-01-16"
  },
  {
      "municipio_id_sus": "431370",
      "municipio_uf": "Palmeira das Missões - RS",
      "cidadao_nome": "AGATHA SOPHIA SILVA MOSSMANN",
      "cidadao_nome_responsavel": "RESPONSÁVEL NÃO IDENTIFICADO",
      "cidadao_cpf_dt_nascimento": "07160456050",
      "cidadao_idade_meses": 5,
      "quadrimestre_completa_1_ano": "2024.Q2",
      "id_status_quadrimestre": 2,
      "data_ou_prazo_1dose_polio": "2023-09-28",
      "data_ou_prazo_2dose_polio": "2023-11-28",
      "data_ou_prazo_3dose_polio": "2024-01-28",
      "id_status_polio": 20,
      "id_cor_1dose_polio": 2,
      "id_cor_2dose_polio": 2,
      "id_cor_3dose_polio": 1,
      "data_ou_prazo_1dose_penta": "2023-09-28",
      "data_ou_prazo_2dose_penta": "2023-11-28",
      "data_ou_prazo_3dose_penta": "2024-01-28",
      "id_status_penta": 2,
      "id_cor_1dose_penta": 2,
      "id_cor_2dose_penta": 2,
      "id_cor_3dose_penta": 1,
      "acs_nome": "SEM VISITA OU CADASTRO",
      "equipe_ine": "0000428442",
      "equipe_nome": "ESF V - MUTIRAO",
      "criacao_data": "2024-01-22",
      "atualizacao_data": "2024-01-22",
      "dt_registro_producao_mais_recente": "2024-01-18"
  },
  {
      "municipio_id_sus": "431370",
      "municipio_uf": "Palmeira das Missões - RS",
      "cidadao_nome": "AGNES MACHADO CAVALHEIRO",
      "cidadao_nome_responsavel": "ALEXANDRE DIONATAN BUENO DA SILVA",
      "cidadao_cpf_dt_nascimento": "07152669007",
      "cidadao_idade_meses": 6,
      "quadrimestre_completa_1_ano": "2024.Q2",
      "id_status_quadrimestre": 2,
      "data_ou_prazo_1dose_polio": "2023-09-21",
      "data_ou_prazo_2dose_polio": "2023-11-27",
      "data_ou_prazo_3dose_polio": "2024-01-27",
      "id_status_polio": 20,
      "id_cor_1dose_polio": 2,
      "id_cor_2dose_polio": 2,
      "id_cor_3dose_polio": 1,
      "data_ou_prazo_1dose_penta": "2023-09-21",
      "data_ou_prazo_2dose_penta": "2023-11-27",
      "data_ou_prazo_3dose_penta": "2024-01-27",
      "id_status_penta": 2,
      "id_cor_1dose_penta": 2,
      "id_cor_2dose_penta": 2,
      "id_cor_3dose_penta": 1,
      "acs_nome": "Eldreia Brandao da Rosa",
      "equipe_ine": "0001634658",
      "equipe_nome": "ESF IX - FUNHPAM",
      "criacao_data": "2024-01-22",
      "atualizacao_data": "2024-01-22",
      "dt_registro_producao_mais_recente": "2024-01-15"
  },
  {
      "municipio_id_sus": "431370",
      "municipio_uf": "Palmeira das Missões - RS",
      "cidadao_nome": "AKIRA EMANUELLY BARBOSA SOARES",
      "cidadao_nome_responsavel": "RESPONSÁVEL NÃO IDENTIFICADO",
      "cidadao_cpf_dt_nascimento": "07133487047",
      "cidadao_idade_meses": 7,
      "quadrimestre_completa_1_ano": "2024.Q2",
      "id_status_quadrimestre": 2,
      "data_ou_prazo_1dose_polio": "2023-08-02",
      "data_ou_prazo_2dose_polio": "2023-10-02",
      "data_ou_prazo_3dose_polio": "2023-12-04",
      "id_status_polio": 10,
      "id_cor_1dose_polio": 2,
      "id_cor_2dose_polio": 2,
      "id_cor_3dose_polio": 2,
      "data_ou_prazo_1dose_penta": "2023-08-02",
      "data_ou_prazo_2dose_penta": "2023-10-02",
      "data_ou_prazo_3dose_penta": "2023-12-08",
      "id_status_penta": 1,
      "id_cor_1dose_penta": 2,
      "id_cor_2dose_penta": 2,
      "id_cor_3dose_penta": 2,
      "acs_nome": "Claudia do Amaral Goncalves de Lara",
      "equipe_ine": "0001496646",
      "equipe_nome": "ESF VII AMARAL",
      "criacao_data": "2024-01-22",
      "atualizacao_data": "2024-01-22",
      "dt_registro_producao_mais_recente": "2024-01-19"
  },
  {
      "municipio_id_sus": "431370",
      "municipio_uf": "Palmeira das Missões - RS",
      "cidadao_nome": "ALEXANDRE KINALSKI SCHWEDE",
      "cidadao_nome_responsavel": "RESPONSÁVEL NÃO IDENTIFICADO",
      "cidadao_cpf_dt_nascimento": "07134187020",
      "cidadao_idade_meses": 7,
      "quadrimestre_completa_1_ano": "2024.Q2",
      "id_status_quadrimestre": 2,
      "data_ou_prazo_1dose_polio": "2023-09-12",
      "data_ou_prazo_2dose_polio": "2023-11-13",
      "data_ou_prazo_3dose_polio": "2024-01-18",
      "id_status_polio": 10,
      "id_cor_1dose_polio": 2,
      "id_cor_2dose_polio": 2,
      "id_cor_3dose_polio": 2,
      "data_ou_prazo_1dose_penta": "2023-09-12",
      "data_ou_prazo_2dose_penta": "2023-11-13",
      "data_ou_prazo_3dose_penta": "2024-01-18",
      "id_status_penta": 1,
      "id_cor_1dose_penta": 2,
      "id_cor_2dose_penta": 2,
      "id_cor_3dose_penta": 2,
      "acs_nome": "SEM VISITA OU CADASTRO",
      "equipe_ine": "-",
      "equipe_nome": "SEM EQUIPE",
      "criacao_data": "2024-01-22",
      "atualizacao_data": "2024-01-22",
      "dt_registro_producao_mais_recente": "2024-01-19"
  },
  {
      "municipio_id_sus": "431370",
      "municipio_uf": "Palmeira das Missões - RS",
      "cidadao_nome": "ALICE ALVES SIMÕES",
      "cidadao_nome_responsavel": "RESPONSÁVEL NÃO IDENTIFICADO",
      "cidadao_cpf_dt_nascimento": "07129772018",
      "cidadao_idade_meses": 7,
      "quadrimestre_completa_1_ano": "2024.Q2",
      "id_status_quadrimestre": 2,
      "data_ou_prazo_1dose_polio": "2023-07-24",
      "data_ou_prazo_2dose_polio": "2023-09-26",
      "data_ou_prazo_3dose_polio": "2023-11-28",
      "id_status_polio": 10,
      "id_cor_1dose_polio": 2,
      "id_cor_2dose_polio": 2,
      "id_cor_3dose_polio": 2,
      "data_ou_prazo_1dose_penta": "2023-07-24",
      "data_ou_prazo_2dose_penta": "2023-09-26",
      "data_ou_prazo_3dose_penta": "2023-11-28",
      "id_status_penta": 1,
      "id_cor_1dose_penta": 2,
      "id_cor_2dose_penta": 2,
      "id_cor_3dose_penta": 2,
      "acs_nome": "SEM VISITA OU CADASTRO",
      "equipe_ine": "0000428361",
      "equipe_nome": "ESV III - CENTRO SOCIAL URBANO",
      "criacao_data": "2024-01-22",
      "atualizacao_data": "2024-01-22",
      "dt_registro_producao_mais_recente": "2024-01-16"
  },
  {
      "municipio_id_sus": "431370",
      "municipio_uf": "Palmeira das Missões - RS",
      "cidadao_nome": "ALICE DIAS BURGO",
      "cidadao_nome_responsavel": "RESPONSÁVEL NÃO IDENTIFICADO",
      "cidadao_cpf_dt_nascimento": "07104236082",
      "cidadao_idade_meses": 9,
      "quadrimestre_completa_1_ano": "2024.Q1",
      "id_status_quadrimestre": 1,
      "data_ou_prazo_1dose_polio": "2023-06-06",
      "data_ou_prazo_2dose_polio": "2023-08-31",
      "data_ou_prazo_3dose_polio": "2023-11-29",
      "id_status_polio": 10,
      "id_cor_1dose_polio": 2,
      "id_cor_2dose_polio": 2,
      "id_cor_3dose_polio": 2,
      "data_ou_prazo_1dose_penta": "2023-06-06",
      "data_ou_prazo_2dose_penta": "2023-08-31",
      "data_ou_prazo_3dose_penta": "2023-11-29",
      "id_status_penta": 1,
      "id_cor_1dose_penta": 2,
      "id_cor_2dose_penta": 2,
      "id_cor_3dose_penta": 2,
      "acs_nome": "SEM VISITA OU CADASTRO",
      "equipe_ine": "0000428418",
      "equipe_nome": "PSF II PALMEIRA DAS MISSOES",
      "criacao_data": "2024-01-22",
      "atualizacao_data": "2024-01-22",
      "dt_registro_producao_mais_recente": "2024-01-18"
  },
  {
      "municipio_id_sus": "431370",
      "municipio_uf": "Palmeira das Missões - RS",
      "cidadao_nome": "ALICE DOS REIS BARRETO",
      "cidadao_nome_responsavel": "RESPONSÁVEL NÃO IDENTIFICADO",
      "cidadao_cpf_dt_nascimento": "07075523031",
      "cidadao_idade_meses": 11,
      "quadrimestre_completa_1_ano": "2024.Q1",
      "id_status_quadrimestre": 1,
      "data_ou_prazo_1dose_polio": "2023-04-05",
      "data_ou_prazo_2dose_polio": "2023-06-22",
      "data_ou_prazo_3dose_polio": "2023-08-02",
      "id_status_polio": 10,
      "id_cor_1dose_polio": 2,
      "id_cor_2dose_polio": 2,
      "id_cor_3dose_polio": 2,
      "data_ou_prazo_1dose_penta": "2023-04-05",
      "data_ou_prazo_2dose_penta": "2023-06-22",
      "data_ou_prazo_3dose_penta": "2023-08-02",
      "id_status_penta": 1,
      "id_cor_1dose_penta": 2,
      "id_cor_2dose_penta": 2,
      "id_cor_3dose_penta": 2,
      "acs_nome": "SEM VISITA OU CADASTRO",
      "equipe_ine": null,
      "equipe_nome": "SEM EQUIPE",
      "criacao_data": "2024-01-22",
      "atualizacao_data": "2024-01-22",
      "dt_registro_producao_mais_recente": null
  },
]
const colunasVacinacaoAPS=[
  {
    align: 'left',
    field: 'cidadao_nome',
    headerAlign: 'center',
    headerName: 'NOME OU RN DE RESPONSÁVEL',
    width: 320,
    sortable : false,
  },
  {
    align: 'left',
    field: 'cidadao_nome_responsavel',
    headerAlign: 'center',
    headerName: 'NOME DO RESPONSÁVEL',
    align : 'center',
    width: 320,
    sortable : false
  },
  {
    align: 'center',
    field: 'cidadao_cpf_dt_nascimento',
    headerName: 'CPF / DATA DE NASCIMENTO',
    align: 'center',
    width: 140,
    sortable : false
  },
  {
    align: 'center',
    field: 'cidadao_idade_meses',
    headerAlign: 'center',
    headerName: 'IDADE (MESES)',
    width: 100,
    sortable : false,
  },
  {
    align: 'center',
    field: 'id_status_polio',
    headerAlign: 'center',
    headerName: 'STATUS DO ESQUEMA POLIO',
    width: 250,
    sortable : false,
  },
  {
    align: 'center',
    field: 'data_ou_prazo_1dose_polio',
    headerAlign: 'center',
    headerName: '1ª DOSE POLIO',
    width: 150,
    sortable : false,
  },
  {
    align: 'center',
    field: 'data_ou_prazo_2dose_polio',
    headerAlign: 'center',
    headerName: '2ª DOSE POLIO',
    width: 150,
    sortable : false,
  },
  {
    align: 'center',
    field: 'data_ou_prazo_3dose_polio',
    headerAlign: 'center',
    headerName: '3ª DOSE POLIO',
    width: 150,
    sortable : false,
  },
  {
      align: 'center',
      field: 'id_status_penta',
      headerAlign: 'center',
      headerName: 'STATUS DO ESQUEMA PENTA',
      width: 250,
      sortable : false,
  },
  {
    align: 'center',
    field: 'data_ou_prazo_1dose_penta',
    headerAlign: 'center',
    headerName: '1ª DOSE PENTA',
    width: 150,
    sortable : false,
  },
  {
    align: 'center',
    field: 'data_ou_prazo_2dose_penta',
    headerAlign: 'center',
    headerName: '2ª DOSE PENTA',
    width: 150,
    sortable : false,
  },
  {
    align: 'center',
    field: 'data_ou_prazo_3dose_penta',
    headerAlign: 'center',
    headerName: '3ª DOSE PENTA',
    width: 150,
    sortable : false,
  },
  {
    align: 'center',
    field: 'acs_nome',
    headerAlign: 'center',
    headerName: 'PROFISSIONAL RESPONSÁVEL',
    width: 300,
    sortable : false
  },
    
]

const Template = (args) => <TabelaVacinacaoImpressao {...args}/>

export const Vacinacao = Template.bind({});

Vacinacao.args={
  data : dataVacinacao,
  colunas : colunasVacinacaoAPS,
  status_usuario_descricao : status_usuario_descricao
}