export const dataDiabetes=[
    {
      "cidadao_nome": "DALVA MARIA CORREIA MENDES",
      "cidadao_cpf_dt_nascimento": "1966-01-18",
      "identificacao_condicao_diabetes": "Autorreferida",
      "dt_consulta_mais_recente": "2022-02-08",
      "prazo_proxima_consulta": "Até 31/Agosto",
      "dt_solicitacao_hemoglobina_glicada_mais_recente": null,
      "prazo_proxima_solicitacao_hemoglobina": "Até 31/Agosto",
      "acs_nome_cadastro": "Soraia",
      "cidadao_idade": 35,
      "equipe_nome_cadastro": "equipe estrela"
    },
    {
      "cidadao_nome": "DESUITA JANSEN",
      "cidadao_cpf_dt_nascimento": "1952-11-12",
      "identificacao_condicao_diabetes": "Diagnóstico Clínico",
      "dt_consulta_mais_recente": null,
      "prazo_proxima_consulta": "Até 31/Agosto",
      "dt_solicitacao_hemoglobina_glicada_mais_recente": null,
      "prazo_proxima_solicitacao_hemoglobina": "Até 31/Agosto",
      "acs_nome_cadastro": "Samira",
      "cidadao_idade": 35,
      "equipe_nome_cadastro": "equipe estrela"
    },
    {
      "cidadao_nome": "EDMILSON CASTRO SILVA",
      "cidadao_cpf_dt_nascimento": "45037680344",
      "identificacao_condicao_diabetes": "Diagnóstico Clínico",
      "dt_consulta_mais_recente": "2023-03-15",
      "prazo_proxima_consulta": "Em dia",
      "dt_solicitacao_hemoglobina_glicada_mais_recente": "2023-03-15",
      "prazo_proxima_solicitacao_hemoglobina": "Em dia",
      "acs_nome_cadastro": "Karliane Cunha Gomes",
      "cidadao_idade": 35,
      "equipe_nome_cadastro": "equipe estrela"
    },
    {
      "cidadao_nome": "GILMARA MACHADO SANTOS",
      "cidadao_cpf_dt_nascimento": "1981-06-11",
      "identificacao_condicao_diabetes": "Diagnóstico Clínico",
      "dt_consulta_mais_recente": "2020-07-27",
      "prazo_proxima_consulta": "Até 31/Agosto",
      "dt_solicitacao_hemoglobina_glicada_mais_recente": null,
      "prazo_proxima_solicitacao_hemoglobina": "Até 31/Agosto",
      "acs_nome_cadastro": "Genilson Nascimento Lindoso",
      "cidadao_idade": 35,
      "equipe_nome_cadastro": "equipe lua"
    },
    {
      "cidadao_nome": "JOAO PEDRO MENDES",
      "cidadao_cpf_dt_nascimento": "1955-05-30",
      "identificacao_condicao_diabetes": "Diagnóstico Clínico",
      "dt_consulta_mais_recente": "2022-04-14",
      "prazo_proxima_consulta": "Até 31/Agosto",
      "dt_solicitacao_hemoglobina_glicada_mais_recente": null,
      "prazo_proxima_solicitacao_hemoglobina": "Até 31/Agosto",
      "acs_nome_cadastro": "Nerita Maia Travassos",
      "cidadao_idade": 35,
      "equipe_nome_cadastro": "equipe lua"
    },
    {
      "cidadao_nome": "JOSE ROBERTO PINHEIRO CAMARA",
      "cidadao_cpf_dt_nascimento": "1976-11-22",
      "identificacao_condicao_diabetes": "Diagnóstico Clínico",
      "dt_consulta_mais_recente": "2021-07-22",
      "prazo_proxima_consulta": "Até 31/Agosto",
      "dt_solicitacao_hemoglobina_glicada_mais_recente": null,
      "prazo_proxima_solicitacao_hemoglobina": "Até 31/Agosto",
      "acs_nome_cadastro": "Ines Pinheiro Costa",
      "cidadao_idade": 35,
      "equipe_nome_cadastro": "equipe lua"
    },
    {
      "cidadao_nome": "RAIMUNDA COSTA DOS SANTOS",
      "cidadao_cpf_dt_nascimento": "1933-03-30",
      "identificacao_condicao_diabetes": "Diagnóstico Clínico",
      "dt_consulta_mais_recente": "2022-09-05",
      "prazo_proxima_consulta": "Até 31/Agosto",
      "dt_solicitacao_hemoglobina_glicada_mais_recente": "2022-09-05",
      "prazo_proxima_solicitacao_hemoglobina": "Até 31/Agosto",
      "acs_nome_cadastro": "Ana Lucia Correa",
      "cidadao_idade": 35,
      "equipe_nome_cadastro": "equipe sol"
    },
    {
      "cidadao_nome": "ADRIEL ARAUJO MENDONCA",
      "cidadao_cpf_dt_nascimento": "2001-08-21",
      "identificacao_condicao_diabetes": "Diagnóstico Clínico",
      "dt_consulta_mais_recente": "2021-07-12",
      "prazo_proxima_consulta": "Até 31/Agosto",
      "dt_solicitacao_hemoglobina_glicada_mais_recente": null,
      "prazo_proxima_solicitacao_hemoglobina": "Até 31/Agosto",
      "acs_nome_cadastro": "Joao Gutemberg Pereira Soeiro",
      "cidadao_idade": 35,
      "equipe_nome_cadastro": "equipe sol"
    },
    {
      "cidadao_nome": "ALEXANDRINA MATA MAIA",
      "cidadao_cpf_dt_nascimento": "1950-05-19",
      "identificacao_condicao_diabetes": "Diagnóstico Clínico",
      "dt_consulta_mais_recente": "2021-08-24",
      "prazo_proxima_consulta": "Até 31/Agosto",
      "dt_solicitacao_hemoglobina_glicada_mais_recente": "2021-08-24",
      "prazo_proxima_solicitacao_hemoglobina": "Até 31/Agosto",
      "acs_nome_cadastro": "Raimundo Rosa Barros",
      "cidadao_idade": 35,
      "equipe_nome_cadastro": "equipe sol"
    },
  ]