export const rotulosfiltrosDiabetes = [
    "NOMES DE A-Z",
    "NOME DO ACS DE A-Z",
    "DATA DA CONSULTA MAIS RECENTE",
    "PRAZO PARA PRÓXIMA CONSULTA",
    "DATA DE SOLICITAÇÃO DE HEMOGLOBINA GLICADA MAIS RECENTE",
    "PRAZO PARA PRÓXIMA SOLICITAÇÃO DE HEMOGLOBINA GLICADA MAIS RECENTE"
  ]