import React from 'react'
import { TabelaImpressao } from '../PainelBuscaAtiva/components/Impressao/componentes/TabelaImpressao';
export default {
  title: "Componentes/TabelaImpressao",
  component: TabelaImpressao,
};

const status_usuario_descricao =  [
  {
    "id_status_usuario" : 0,
    "status_usuario_descricao" : "Sem dados",
    "atualizacao_data" : "2023-05-02T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 1,
    "status_usuario_descricao" : "Com consulta e aferição de PA em dia",
    "atualizacao_data" : "2023-05-02T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 2,
    "status_usuario_descricao" : "Sem consulta e aferição de PA em dia",
    "atualizacao_data" : "2023-05-02T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 3,
    "status_usuario_descricao" : "Sem consulta em dia",
    "atualizacao_data" : "2023-05-02T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 4,
    "status_usuario_descricao" : "Sem aferição de PA em dia",
    "atualizacao_data" : "2023-05-02T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 5,
    "status_usuario_descricao" : "Com consulta e solicitação de hemoglobina em dia",
    "atualizacao_data" : "2023-05-02T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 6,
    "status_usuario_descricao" : "Sem consulta e solicitação de hemoglobina em dia",
    "atualizacao_data" : "2023-05-02T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 7,
    "status_usuario_descricao" : "Sem solicitação de hemoglobina em dia",
    "atualizacao_data" : "2023-05-02T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 8,
    "status_usuario_descricao" : "Encerradas por DPP + 14 dias",
    "atualizacao_data" : "2023-05-02T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 9,
    "status_usuario_descricao" : "Encerradas por parto ou aborto",
    "atualizacao_data" : "2023-05-15T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 10,
    "status_usuario_descricao" : "Ativas",
    "atualizacao_data" : "2023-05-15T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 11,
    "status_usuario_descricao" : "Gestantes inválidas",
    "atualizacao_data" : "2023-05-15T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 12,
    "status_usuario_descricao" : "Coleta em dia",
    "atualizacao_data" : "2023-07-03T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 13,
    "status_usuario_descricao" : "Nunca realizou coleta",
    "atualizacao_data" : "2023-07-03T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 14,
    "status_usuario_descricao" : "Coleta com menos de 25 anos",
    "atualizacao_data" : "2023-07-03T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 15,
    "status_usuario_descricao" : "Vence no final do quadrimestre",
    "atualizacao_data" : "2023-07-03T03:00:00.000Z"
  },
  {
    "id_status_usuario" : 16,
    "status_usuario_descricao" : "Coleta vencida",
    "atualizacao_data" : "2023-07-03T03:00:00.000Z"
  }
]

const dataCito = [
    {
        "paciente_nome": "ACIONE ADORNO AFONSO",
        "cidadao_cpf_dt_nascimento": "48244809114",
        "id_status_usuario": 16,
        "vencimento_da_coleta": "29/05/2022",
        "prazo_proxima_coleta": "31/08/2024",
        "idade": 45,
        "id_faixa_etaria": 7,
        "acs_nome": "VANDERLEYA ALBUQUERQUE ALEXANDRE",
        "estabelecimento_cnes": "3068927",
        "estabelecimento_nome": "UBS Diminiz Diniz da Silva",
        "equipe_ine": "0000016004",
        "ine_master": "0000016004",
        "equipe_nome": "ESF DIMINIZ",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ACIONE BRASIL MENEGASSO",
        "cidadao_cpf_dt_nascimento": "68528996567",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "26/04/2026",
        "prazo_proxima_coleta": "Em dia",
        "idade": 31,
        "id_faixa_etaria": 6,
        "acs_nome": "FLORINDA DUTRA BRUNO",
        "estabelecimento_cnes": "2320088",
        "estabelecimento_nome": "UBS Alessandra Rosas Sarmento Nova Esperanca",
        "equipe_ine": "0000015989",
        "ine_master": "0000015989",
        "equipe_nome": "ESF NOVA ESPERANCA",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADA AGIAR AGUIAR",
        "cidadao_cpf_dt_nascimento": "91584621039",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "04/08/2025",
        "prazo_proxima_coleta": "Em dia",
        "idade": 37,
        "id_faixa_etaria": 6,
        "acs_nome": "ORIANA LANFRANCO BRASILEIRO",
        "estabelecimento_cnes": "3068927",
        "estabelecimento_nome": "UBS Diminiz Diniz da Silva",
        "equipe_ine": "0000016004",
        "ine_master": "0000016004",
        "equipe_nome": "ESF DIMINIZ",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADALGISA BRAZIL MENEZES",
        "cidadao_cpf_dt_nascimento": "87678869824",
        "id_status_usuario": 13,
        "vencimento_da_coleta": "-",
        "prazo_proxima_coleta": "31/08/2024",
        "idade": 62,
        "id_faixa_etaria": 8,
        "acs_nome": "JUMEIRE AUGUSTO GOMES",
        "estabelecimento_cnes": "2320053",
        "estabelecimento_nome": "Centro de Saude Cristino Jose da Silva",
        "equipe_ine": "0000015962",
        "ine_master": "0000015962",
        "equipe_nome": "ESF CRISTINO",
        "dt_registro_producao_mais_recente": "2024-07-29"
    },
    {
        "paciente_nome": "ADEILZA BRITO MIGUEL",
        "cidadao_cpf_dt_nascimento": "50963941138",
        "id_status_usuario": 13,
        "vencimento_da_coleta": "-",
        "prazo_proxima_coleta": "31/08/2024",
        "idade": 25,
        "id_faixa_etaria": 6,
        "acs_nome": "SIRLEI REAL MENDANHA",
        "estabelecimento_cnes": "2320053",
        "estabelecimento_nome": "Centro de Saude Cristino Jose da Silva",
        "equipe_ine": "0000015962",
        "ine_master": "0000015962",
        "equipe_nome": "ESF CRISTINO",
        "dt_registro_producao_mais_recente": "2024-07-29"
    },
    {
        "paciente_nome": "ADEISA DIVINO CHUNHA",
        "cidadao_cpf_dt_nascimento": "52789745524",
        "id_status_usuario": 13,
        "vencimento_da_coleta": "-",
        "prazo_proxima_coleta": "31/08/2024",
        "idade": 31,
        "id_faixa_etaria": 6,
        "acs_nome": "MATILDES CICERONE NACIMENTO",
        "estabelecimento_cnes": "2320029",
        "estabelecimento_nome": "UBS Maria Jandira Vieira Peixoto Sao Francisco",
        "equipe_ine": "0000015954",
        "ine_master": "0000015954",
        "equipe_nome": "ESF SAO FRANCISCO",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADEISA JACO SALDANHA",
        "cidadao_cpf_dt_nascimento": "53018661647",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "30/08/2025",
        "prazo_proxima_coleta": "Em dia",
        "idade": 55,
        "id_faixa_etaria": 8,
        "acs_nome": "FRANCIELLE IGNES FRUTUOSO",
        "estabelecimento_cnes": "2320053",
        "estabelecimento_nome": "Centro de Saude Cristino Jose da Silva",
        "equipe_ine": "0000015962",
        "ine_master": "0000015962",
        "equipe_nome": "ESF CRISTINO",
        "dt_registro_producao_mais_recente": "2024-07-29"
    },
    {
        "paciente_nome": "ADELAIDE DO CLARINDO",
        "cidadao_cpf_dt_nascimento": "65697764129",
        "id_status_usuario": 13,
        "vencimento_da_coleta": "-",
        "prazo_proxima_coleta": "31/08/2024",
        "idade": 53,
        "id_faixa_etaria": 8,
        "acs_nome": "ADOLFO GUIMARÃES NERY",
        "estabelecimento_cnes": "2320053",
        "estabelecimento_nome": "Centro de Saude Cristino Jose da Silva",
        "equipe_ine": "0000015962",
        "ine_master": "0000015962",
        "equipe_nome": "ESF CRISTINO",
        "dt_registro_producao_mais_recente": "2024-07-29"
    },
    {
        "paciente_nome": "ADELAIDE JACOBINA SALES",
        "cidadao_cpf_dt_nascimento": "79913214892",
        "id_status_usuario": 16,
        "vencimento_da_coleta": "14/06/2021",
        "prazo_proxima_coleta": "31/08/2024",
        "idade": 44,
        "id_faixa_etaria": 7,
        "acs_nome": "MARIENE BUFFON LUZ",
        "estabelecimento_cnes": "2320088",
        "estabelecimento_nome": "UBS Alessandra Rosas Sarmento Nova Esperanca",
        "equipe_ine": "0000015989",
        "ine_master": "0000015989",
        "equipe_nome": "ESF NOVA ESPERANCA",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADELAINE DOMINGO CLAUDIA",
        "cidadao_cpf_dt_nascimento": "15564541530",
        "id_status_usuario": 13,
        "vencimento_da_coleta": "-",
        "prazo_proxima_coleta": "31/08/2024",
        "idade": 51,
        "id_faixa_etaria": 8,
        "acs_nome": "JOCINELMA ASSUNÇAO GODIN",
        "estabelecimento_cnes": "2320088",
        "estabelecimento_nome": "UBS Alessandra Rosas Sarmento Nova Esperanca",
        "equipe_ine": "0000015989",
        "ine_master": "0000015989",
        "equipe_nome": "ESF NOVA ESPERANCA",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADELAINE JACOME SALU",
        "cidadao_cpf_dt_nascimento": "59626130293",
        "id_status_usuario": 13,
        "vencimento_da_coleta": "-",
        "prazo_proxima_coleta": "31/08/2024",
        "idade": 38,
        "id_faixa_etaria": 6,
        "acs_nome": "ACACIA FILHA LUCIO",
        "estabelecimento_cnes": null,
        "estabelecimento_nome": null,
        "equipe_ine": "0",
        "ine_master": "0",
        "equipe_nome": "SEM EQUIPE RESPONSÁVEL",
        "dt_registro_producao_mais_recente": "2024-01-25"
    },
    {
        "paciente_nome": "ADELCY ALCANTRA ALMEIDA",
        "cidadao_cpf_dt_nascimento": "82631163277",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "10/10/2025",
        "prazo_proxima_coleta": "Em dia",
        "idade": 60,
        "id_faixa_etaria": 8,
        "acs_nome": "BRENDA JOANA PELEGRINE",
        "estabelecimento_cnes": "2320029",
        "estabelecimento_nome": "UBS Maria Jandira Vieira Peixoto Sao Francisco",
        "equipe_ine": "0000015954",
        "ine_master": "0000015954",
        "equipe_nome": "ESF SAO FRANCISCO",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADELCY CABRAL MONTE",
        "cidadao_cpf_dt_nascimento": "99945846789",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "04/12/2026",
        "prazo_proxima_coleta": "Em dia",
        "idade": 25,
        "id_faixa_etaria": 6,
        "acs_nome": "JIDALVA WANDERLEY DARY",
        "estabelecimento_cnes": "3068927",
        "estabelecimento_nome": "UBS Diminiz Diniz da Silva",
        "equipe_ine": "0000016004",
        "ine_master": "0000016004",
        "equipe_nome": "ESF DIMINIZ",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADELCY JAMBEIRO SALUSTINO",
        "cidadao_cpf_dt_nascimento": "36495369634",
        "id_status_usuario": 13,
        "vencimento_da_coleta": "-",
        "prazo_proxima_coleta": "31/08/2024",
        "idade": 35,
        "id_faixa_etaria": 6,
        "acs_nome": "HÉLIO HONORATO FRUTUOSO",
        "estabelecimento_cnes": "3068927",
        "estabelecimento_nome": "UBS Diminiz Diniz da Silva",
        "equipe_ine": "0000016004",
        "ine_master": "0000016004",
        "equipe_nome": "ESF DIMINIZ",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADELIANE DOS CLEMENTINO",
        "cidadao_cpf_dt_nascimento": "75689691132",
        "id_status_usuario": 13,
        "vencimento_da_coleta": "-",
        "prazo_proxima_coleta": "31/08/2024",
        "idade": 37,
        "id_faixa_etaria": 6,
        "acs_nome": "IRACIR MACEDO LUCENA",
        "estabelecimento_cnes": "2320029",
        "estabelecimento_nome": "UBS Maria Jandira Vieira Peixoto Sao Francisco",
        "equipe_ine": "0000015954",
        "ine_master": "0000015954",
        "equipe_nome": "ESF SAO FRANCISCO",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADELINA CALASANS MORAES",
        "cidadao_cpf_dt_nascimento": "46425409588",
        "id_status_usuario": 13,
        "vencimento_da_coleta": "-",
        "prazo_proxima_coleta": "31/08/2024",
        "idade": 34,
        "id_faixa_etaria": 6,
        "acs_nome": "JONILSON STAVALE BRASILIO",
        "estabelecimento_cnes": "2320088",
        "estabelecimento_nome": "UBS Alessandra Rosas Sarmento Nova Esperanca",
        "equipe_ine": "0000015989",
        "ine_master": "0000015989",
        "equipe_nome": "ESF NOVA ESPERANCA",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADELMA ALNEIDA AMARAL",
        "cidadao_cpf_dt_nascimento": "56087650285",
        "id_status_usuario": 13,
        "vencimento_da_coleta": "-",
        "prazo_proxima_coleta": "31/08/2024",
        "idade": 27,
        "id_faixa_etaria": 6,
        "acs_nome": "EUVIRA FIUSA CONCEICAO",
        "estabelecimento_cnes": "2320029",
        "estabelecimento_nome": "UBS Maria Jandira Vieira Peixoto Sao Francisco",
        "equipe_ine": "0000015954",
        "ine_master": "0000015954",
        "equipe_nome": "ESF SAO FRANCISCO",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADEMILDE DRUZ CONCEIÇÃO",
        "cidadao_cpf_dt_nascimento": "34712018556",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "29/12/2026",
        "prazo_proxima_coleta": "Em dia",
        "idade": 40,
        "id_faixa_etaria": 7,
        "acs_nome": "TERESA BENDER BRETAS",
        "estabelecimento_cnes": "2319888",
        "estabelecimento_nome": "UBS Estevam Pereira da Costa Tucano",
        "equipe_ine": "0001590324",
        "ine_master": "0001590324",
        "equipe_nome": "ESF TUCANO",
        "dt_registro_producao_mais_recente": "2024-07-25"
    },
    {
        "paciente_nome": "ADENEIA ALVES AMBROZIO",
        "cidadao_cpf_dt_nascimento": "13100302447",
        "id_status_usuario": 13,
        "vencimento_da_coleta": "-",
        "prazo_proxima_coleta": "31/08/2024",
        "idade": 47,
        "id_faixa_etaria": 7,
        "acs_nome": "VALDINES CARMO DAVID",
        "estabelecimento_cnes": "2319888",
        "estabelecimento_nome": "UBS Estevam Pereira da Costa Tucano",
        "equipe_ine": "0001590324",
        "ine_master": "0001590324",
        "equipe_nome": "ESF TUCANO",
        "dt_registro_producao_mais_recente": "2024-07-25"
    },
    {
        "paciente_nome": "ADENILIA JESUS SARAIVA",
        "cidadao_cpf_dt_nascimento": "44930829790",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "31/10/2026",
        "prazo_proxima_coleta": "Em dia",
        "idade": 64,
        "id_faixa_etaria": 8,
        "acs_nome": "EDICELIA BENTO RESPLANDE",
        "estabelecimento_cnes": "2320053",
        "estabelecimento_nome": "Centro de Saude Cristino Jose da Silva",
        "equipe_ine": "0000015962",
        "ine_master": "0000015962",
        "equipe_nome": "ESF CRISTINO",
        "dt_registro_producao_mais_recente": "2024-07-29"
    },
    {
        "paciente_nome": "ADENIR ALVIS ANDRADRE",
        "cidadao_cpf_dt_nascimento": "56866678286",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "08/08/2025",
        "prazo_proxima_coleta": "Em dia",
        "idade": 54,
        "id_faixa_etaria": 8,
        "acs_nome": "ANAILDE LINDO SAEGH",
        "estabelecimento_cnes": "2589966",
        "estabelecimento_nome": "UBS Raimundo de Sousa Lima Vilena",
        "equipe_ine": "0000015997",
        "ine_master": "0000015997",
        "equipe_nome": "ESF VILENA",
        "dt_registro_producao_mais_recente": "2024-07-23"
    },
    {
        "paciente_nome": "ADENISIA CAMILO NASCIME",
        "cidadao_cpf_dt_nascimento": "18061080763",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "26/10/2025",
        "prazo_proxima_coleta": "Em dia",
        "idade": 52,
        "id_faixa_etaria": 8,
        "acs_nome": "LINA FALCAO ROSARIO",
        "estabelecimento_cnes": "3068927",
        "estabelecimento_nome": "UBS Diminiz Diniz da Silva",
        "equipe_ine": "0000016004",
        "ine_master": "0000016004",
        "equipe_nome": "ESF DIMINIZ",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADENIZIA CANDIDO NEO",
        "cidadao_cpf_dt_nascimento": "14040169221",
        "id_status_usuario": 13,
        "vencimento_da_coleta": "-",
        "prazo_proxima_coleta": "31/08/2024",
        "idade": 32,
        "id_faixa_etaria": 6,
        "acs_nome": "JAILDE NERING PARDIN",
        "estabelecimento_cnes": "2320088",
        "estabelecimento_nome": "UBS Alessandra Rosas Sarmento Nova Esperanca",
        "equipe_ine": "0000015989",
        "ine_master": "0000015989",
        "equipe_nome": "ESF NOVA ESPERANCA",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADICEIA CÂNDIDO NERES",
        "cidadao_cpf_dt_nascimento": "57013793378",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "05/12/2026",
        "prazo_proxima_coleta": "Em dia",
        "idade": 55,
        "id_faixa_etaria": 8,
        "acs_nome": "ROSINALDO TORRADO SALDANHA",
        "estabelecimento_cnes": "3068927",
        "estabelecimento_nome": "UBS Diminiz Diniz da Silva",
        "equipe_ine": "0000016004",
        "ine_master": "0000016004",
        "equipe_nome": "ESF DIMINIZ",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADICELIA ANASTACIO ARAUJO",
        "cidadao_cpf_dt_nascimento": "45144562365",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "20/02/2027",
        "prazo_proxima_coleta": "Em dia",
        "idade": 31,
        "id_faixa_etaria": 6,
        "acs_nome": "DIONÍZIO SALVIANO FILHO",
        "estabelecimento_cnes": "2320029",
        "estabelecimento_nome": "UBS Maria Jandira Vieira Peixoto Sao Francisco",
        "equipe_ine": "0000015954",
        "ine_master": "0000015954",
        "equipe_nome": "ESF SAO FRANCISCO",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADILA CARDIM NETO",
        "cidadao_cpf_dt_nascimento": "66943784372",
        "id_status_usuario": 13,
        "vencimento_da_coleta": "-",
        "prazo_proxima_coleta": "31/08/2024",
        "idade": 54,
        "id_faixa_etaria": 8,
        "acs_nome": "LUSINETE DEMEDA PEREIRA",
        "estabelecimento_cnes": "2589966",
        "estabelecimento_nome": "UBS Raimundo de Sousa Lima Vilena",
        "equipe_ine": "0000015997",
        "ine_master": "0000015997",
        "equipe_nome": "ESF VILENA",
        "dt_registro_producao_mais_recente": "2024-07-23"
    },
    {
        "paciente_nome": "ADILAINE FARIA DA",
        "cidadao_cpf_dt_nascimento": "15325221256",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "25/04/2026",
        "prazo_proxima_coleta": "Em dia",
        "idade": 36,
        "id_faixa_etaria": 6,
        "acs_nome": "UILMA BRAGA CASTRO",
        "estabelecimento_cnes": "3068927",
        "estabelecimento_nome": "UBS Diminiz Diniz da Silva",
        "equipe_ine": "0000016004",
        "ine_master": "0000016004",
        "equipe_nome": "ESF DIMINIZ",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADILA LADISLAU SENA",
        "cidadao_cpf_dt_nascimento": "24902870038",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "30/08/2025",
        "prazo_proxima_coleta": "Em dia",
        "idade": 35,
        "id_faixa_etaria": 6,
        "acs_nome": "KESIA COSTS NOQUEIRA",
        "estabelecimento_cnes": "2319888",
        "estabelecimento_nome": "UBS Estevam Pereira da Costa Tucano",
        "equipe_ine": "0001590324",
        "ine_master": "0001590324",
        "equipe_nome": "ESF TUCANO",
        "dt_registro_producao_mais_recente": "2024-07-25"
    },
    {
        "paciente_nome": "ADILANE LAGES SEVERIANO",
        "cidadao_cpf_dt_nascimento": "68793559441",
        "id_status_usuario": 13,
        "vencimento_da_coleta": "-",
        "prazo_proxima_coleta": "31/08/2024",
        "idade": 25,
        "id_faixa_etaria": 6,
        "acs_nome": "DIRCELIA VERISSIMO MALHEIRO",
        "estabelecimento_cnes": "2320088",
        "estabelecimento_nome": "UBS Alessandra Rosas Sarmento Nova Esperanca",
        "equipe_ine": "0000015989",
        "ine_master": "0000015989",
        "equipe_nome": "ESF NOVA ESPERANCA",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADILCIA ANDRAFE ASSIS",
        "cidadao_cpf_dt_nascimento": "38235211638",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "13/11/2026",
        "prazo_proxima_coleta": "Em dia",
        "idade": 33,
        "id_faixa_etaria": 6,
        "acs_nome": "NAILDA GOULART ABREU",
        "estabelecimento_cnes": "2320029",
        "estabelecimento_nome": "UBS Maria Jandira Vieira Peixoto Sao Francisco",
        "equipe_ine": "0000015954",
        "ine_master": "0000015954",
        "equipe_nome": "ESF SAO FRANCISCO",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADILEIA CARNEIRO NOBREGA",
        "cidadao_cpf_dt_nascimento": "88064774577",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "02/04/2027",
        "prazo_proxima_coleta": "Em dia",
        "idade": 56,
        "id_faixa_etaria": 8,
        "acs_nome": "JENAILTON ALENCAR FIGUEIRA",
        "estabelecimento_cnes": "3068927",
        "estabelecimento_nome": "UBS Diminiz Diniz da Silva",
        "equipe_ine": "0000016004",
        "ine_master": "0000016004",
        "equipe_nome": "ESF DIMINIZ",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADILENE LAPES SILA",
        "cidadao_cpf_dt_nascimento": "79838913119",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "29/12/2026",
        "prazo_proxima_coleta": "Em dia",
        "idade": 41,
        "id_faixa_etaria": 7,
        "acs_nome": "ELEGIANIA AGUILLERA NAVES",
        "estabelecimento_cnes": "2319888",
        "estabelecimento_nome": "UBS Estevam Pereira da Costa Tucano",
        "equipe_ine": "0001590324",
        "ine_master": "0001590324",
        "equipe_nome": "ESF TUCANO",
        "dt_registro_producao_mais_recente": "2024-07-25"
    },
    {
        "paciente_nome": "ADILEUSA LARANJEIRA SILLVA",
        "cidadao_cpf_dt_nascimento": "41434264764",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "18/07/2026",
        "prazo_proxima_coleta": "Em dia",
        "idade": 30,
        "id_faixa_etaria": 6,
        "acs_nome": "JANE ROSA VIERA",
        "estabelecimento_cnes": "3068927",
        "estabelecimento_nome": "UBS Diminiz Diniz da Silva",
        "equipe_ine": "0000016004",
        "ine_master": "0000016004",
        "equipe_nome": "ESF DIMINIZ",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADIR ANUNCIAÇÃO BARBOZA",
        "cidadao_cpf_dt_nascimento": "75221765541",
        "id_status_usuario": 13,
        "vencimento_da_coleta": "-",
        "prazo_proxima_coleta": "31/08/2024",
        "idade": 34,
        "id_faixa_etaria": 6,
        "acs_nome": "EDICELIA VITO MEDEIROS",
        "estabelecimento_cnes": "3068927",
        "estabelecimento_nome": "UBS Diminiz Diniz da Silva",
        "equipe_ine": "0000016004",
        "ine_master": "0000016004",
        "equipe_nome": "ESF DIMINIZ",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADIRCE APARECIDA BARRETO",
        "cidadao_cpf_dt_nascimento": "23935048680",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "14/11/2025",
        "prazo_proxima_coleta": "Em dia",
        "idade": 61,
        "id_faixa_etaria": 8,
        "acs_nome": "HELOISA RAINHA TEXEIRA",
        "estabelecimento_cnes": "2320053",
        "estabelecimento_nome": "Centro de Saude Cristino Jose da Silva",
        "equipe_ine": "0000015962",
        "ine_master": "0000015962",
        "equipe_nome": "ESF CRISTINO",
        "dt_registro_producao_mais_recente": "2024-07-29"
    },
    {
        "paciente_nome": "ADIRCE CAVALCANTE OLEVEIRA",
        "cidadao_cpf_dt_nascimento": "91438847072",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "20/03/2027",
        "prazo_proxima_coleta": "Em dia",
        "idade": 49,
        "id_faixa_etaria": 7,
        "acs_nome": "HONORIO ROMANINI VENANCIO",
        "estabelecimento_cnes": "2320029",
        "estabelecimento_nome": "UBS Maria Jandira Vieira Peixoto Sao Francisco",
        "equipe_ine": "0000015954",
        "ine_master": "0000015954",
        "equipe_nome": "ESF SAO FRANCISCO",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADISLENE LIBORIO SIMPLICIO",
        "cidadao_cpf_dt_nascimento": "17141934359",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "11/04/2026",
        "prazo_proxima_coleta": "Em dia",
        "idade": 51,
        "id_faixa_etaria": 8,
        "acs_nome": "JONAS ALBANAN FERREIRA",
        "estabelecimento_cnes": "2320053",
        "estabelecimento_nome": "Centro de Saude Cristino Jose da Silva",
        "equipe_ine": "0000015962",
        "ine_master": "0000015962",
        "equipe_nome": "ESF CRISTINO",
        "dt_registro_producao_mais_recente": "2024-07-29"
    },
    {
        "paciente_nome": "ADIVANIA CEDRIM OLIVEIRARA",
        "cidadao_cpf_dt_nascimento": "76642635435",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "18/08/2025",
        "prazo_proxima_coleta": "Em dia",
        "idade": 57,
        "id_faixa_etaria": 8,
        "acs_nome": "IVANEIDE SCUDERO ATAIDE",
        "estabelecimento_cnes": "2320029",
        "estabelecimento_nome": "UBS Maria Jandira Vieira Peixoto Sao Francisco",
        "equipe_ine": "0000015954",
        "ine_master": "0000015954",
        "equipe_nome": "ESF SAO FRANCISCO",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADIVANIA FERREIRA DUARTE",
        "cidadao_cpf_dt_nascimento": "40458706011",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "07/12/2024",
        "prazo_proxima_coleta": "Em dia",
        "idade": 54,
        "id_faixa_etaria": 8,
        "acs_nome": "VERIDIANA ARAÚJO BALDOINO",
        "estabelecimento_cnes": "2320053",
        "estabelecimento_nome": "Centro de Saude Cristino Jose da Silva",
        "equipe_ine": "0000015962",
        "ine_master": "0000015962",
        "equipe_nome": "ESF CRISTINO",
        "dt_registro_producao_mais_recente": "2024-07-29"
    },
    {
        "paciente_nome": "ADMA FERREIRAFERNANDES DUNGA",
        "cidadao_cpf_dt_nascimento": "85076953470",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "26/04/2027",
        "prazo_proxima_coleta": "Em dia",
        "idade": 40,
        "id_faixa_etaria": 7,
        "acs_nome": "DAMIZIA NOGUEIRS BARROS",
        "estabelecimento_cnes": "2320088",
        "estabelecimento_nome": "UBS Alessandra Rosas Sarmento Nova Esperanca",
        "equipe_ine": "0000015989",
        "ine_master": "0000015989",
        "equipe_nome": "ESF NOVA ESPERANCA",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADMA LINO SLVA",
        "cidadao_cpf_dt_nascimento": "75425920446",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "30/04/2027",
        "prazo_proxima_coleta": "Em dia",
        "idade": 51,
        "id_faixa_etaria": 8,
        "acs_nome": "ABENAILDA AGE AGUIAR",
        "estabelecimento_cnes": "2320053",
        "estabelecimento_nome": "Centro de Saude Cristino Jose da Silva",
        "equipe_ine": "0000015962",
        "ine_master": "0000015962",
        "equipe_nome": "ESF CRISTINO",
        "dt_registro_producao_mais_recente": "2024-07-29"
    },
    {
        "paciente_nome": "ADNA FERRERA ELOY",
        "cidadao_cpf_dt_nascimento": "48247385562",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "30/08/2025",
        "prazo_proxima_coleta": "Em dia",
        "idade": 34,
        "id_faixa_etaria": 6,
        "acs_nome": "MARISDETE CARLOS MENDANHA",
        "estabelecimento_cnes": "2589966",
        "estabelecimento_nome": "UBS Raimundo de Sousa Lima Vilena",
        "equipe_ine": "0000015997",
        "ine_master": "0000015997",
        "equipe_nome": "ESF VILENA",
        "dt_registro_producao_mais_recente": "2024-07-23"
    },
    {
        "paciente_nome": "ADNEIA CENA OLUVEIRA",
        "cidadao_cpf_dt_nascimento": "88844201646",
        "id_status_usuario": 16,
        "vencimento_da_coleta": "03/10/2021",
        "prazo_proxima_coleta": "31/08/2024",
        "idade": 29,
        "id_faixa_etaria": 6,
        "acs_nome": "VANESSA ALVAREZ AMORIM",
        "estabelecimento_cnes": "2320053",
        "estabelecimento_nome": "Centro de Saude Cristino Jose da Silva",
        "equipe_ine": "0000015962",
        "ine_master": "0000015962",
        "equipe_nome": "ESF CRISTINO",
        "dt_registro_producao_mais_recente": "2024-07-29"
    },
    {
        "paciente_nome": "ADRIANA CESARIO PAIVA",
        "cidadao_cpf_dt_nascimento": "29748926732",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "07/12/2025",
        "prazo_proxima_coleta": "Em dia",
        "idade": 35,
        "id_faixa_etaria": 6,
        "acs_nome": "CRISTINA MUNIZ AQUINO",
        "estabelecimento_cnes": "2320088",
        "estabelecimento_nome": "UBS Alessandra Rosas Sarmento Nova Esperanca",
        "equipe_ine": "0000015989",
        "ine_master": "0000015989",
        "equipe_nome": "ESF NOVA ESPERANCA",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADRIANA LOBO SOIZA",
        "cidadao_cpf_dt_nascimento": "55983249743",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "30/03/2026",
        "prazo_proxima_coleta": "Em dia",
        "idade": 38,
        "id_faixa_etaria": 6,
        "acs_nome": "GENERINA FLORIANO CORREA",
        "estabelecimento_cnes": "2319888",
        "estabelecimento_nome": "UBS Estevam Pereira da Costa Tucano",
        "equipe_ine": "0001590324",
        "ine_master": "0001590324",
        "equipe_nome": "ESF TUCANO",
        "dt_registro_producao_mais_recente": "2024-07-25"
    },
    {
        "paciente_nome": "ADRIANI FIGUEREDO EVARISTO",
        "cidadao_cpf_dt_nascimento": "19177903577",
        "id_status_usuario": 16,
        "vencimento_da_coleta": "25/01/2024",
        "prazo_proxima_coleta": "31/08/2024",
        "idade": 46,
        "id_faixa_etaria": 7,
        "acs_nome": "ADEILSON CORNALBAS FONSCCA",
        "estabelecimento_cnes": "2320029",
        "estabelecimento_nome": "UBS Maria Jandira Vieira Peixoto Sao Francisco",
        "equipe_ine": "0000015954",
        "ine_master": "0000015954",
        "equipe_nome": "ESF SAO FRANCISCO",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADRIANI LOMES SOUSA",
        "cidadao_cpf_dt_nascimento": "29062296259",
        "id_status_usuario": 13,
        "vencimento_da_coleta": "-",
        "prazo_proxima_coleta": "31/08/2024",
        "idade": 30,
        "id_faixa_etaria": 6,
        "acs_nome": "EDILANI ANTONIO PALMEIRA",
        "estabelecimento_cnes": "3068927",
        "estabelecimento_nome": "UBS Diminiz Diniz da Silva",
        "equipe_ine": "0000016004",
        "ine_master": "0000016004",
        "equipe_nome": "ESF DIMINIZ",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADRIANNE CHAGAS PASCOAL",
        "cidadao_cpf_dt_nascimento": "25927024593",
        "id_status_usuario": 13,
        "vencimento_da_coleta": "-",
        "prazo_proxima_coleta": "31/08/2024",
        "idade": 35,
        "id_faixa_etaria": 6,
        "acs_nome": "HERMIRA PENA ROMAO",
        "estabelecimento_cnes": "2320053",
        "estabelecimento_nome": "Centro de Saude Cristino Jose da Silva",
        "equipe_ine": "0000015962",
        "ine_master": "0000015962",
        "equipe_nome": "ESF CRISTINO",
        "dt_registro_producao_mais_recente": "2024-07-29"
    },
    {
        "paciente_nome": "ADRIANO LOPES SOUZA",
        "cidadao_cpf_dt_nascimento": "93523622233",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "17/10/2026",
        "prazo_proxima_coleta": "Em dia",
        "idade": 25,
        "id_faixa_etaria": 6,
        "acs_nome": "INDIANA RAZZINE TRANQUEIRA",
        "estabelecimento_cnes": "3068927",
        "estabelecimento_nome": "UBS Diminiz Diniz da Silva",
        "equipe_ine": "0000016004",
        "ine_master": "0000016004",
        "equipe_nome": "ESF DIMINIZ",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADRIANY ARRUDA BERNARDO",
        "cidadao_cpf_dt_nascimento": "31587203292",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "11/12/2026",
        "prazo_proxima_coleta": "Em dia",
        "idade": 49,
        "id_faixa_etaria": 7,
        "acs_nome": "LAURENTINO ZEFERINO EVANGELISTA",
        "estabelecimento_cnes": "2320088",
        "estabelecimento_nome": "UBS Alessandra Rosas Sarmento Nova Esperanca",
        "equipe_ine": "0000015989",
        "ine_master": "0000015989",
        "equipe_nome": "ESF NOVA ESPERANCA",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADRIELLE CIRQUEIRA PAZ",
        "cidadao_cpf_dt_nascimento": "52270156690",
        "id_status_usuario": 13,
        "vencimento_da_coleta": "-",
        "prazo_proxima_coleta": "31/08/2024",
        "idade": 41,
        "id_faixa_etaria": 7,
        "acs_nome": "CRISPIM PULCINO COUTO",
        "estabelecimento_cnes": "2320088",
        "estabelecimento_nome": "UBS Alessandra Rosas Sarmento Nova Esperanca",
        "equipe_ine": "0000015989",
        "ine_master": "0000015989",
        "equipe_nome": "ESF NOVA ESPERANCA",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADRIELY LUDWIG TINTINO",
        "cidadao_cpf_dt_nascimento": "96611121075",
        "id_status_usuario": 13,
        "vencimento_da_coleta": "-",
        "prazo_proxima_coleta": "31/08/2024",
        "idade": 26,
        "id_faixa_etaria": 6,
        "acs_nome": "JONATAS ALBARRAM FERRREIRA",
        "estabelecimento_cnes": null,
        "estabelecimento_nome": null,
        "equipe_ine": "0",
        "ine_master": "0",
        "equipe_nome": "SEM EQUIPE RESPONSÁVEL",
        "dt_registro_producao_mais_recente": "2024-01-25"
    },
    {
        "paciente_nome": "ADRILANE FONTOURA FERMANDES",
        "cidadao_cpf_dt_nascimento": "19353376955",
        "id_status_usuario": 16,
        "vencimento_da_coleta": "09/07/2022",
        "prazo_proxima_coleta": "31/08/2024",
        "idade": 27,
        "id_faixa_etaria": 6,
        "acs_nome": "OLDEMAR NOGUEIRS GLORIA",
        "estabelecimento_cnes": "2320053",
        "estabelecimento_nome": "Centro de Saude Cristino Jose da Silva",
        "equipe_ine": "0000015962",
        "ine_master": "0000015962",
        "equipe_nome": "ESF CRISTINO",
        "dt_registro_producao_mais_recente": "2024-07-29"
    },
    {
        "paciente_nome": "ADRILANE LUÍZA TORRES",
        "cidadao_cpf_dt_nascimento": "60029223827",
        "id_status_usuario": 13,
        "vencimento_da_coleta": "-",
        "prazo_proxima_coleta": "31/08/2024",
        "idade": 35,
        "id_faixa_etaria": 6,
        "acs_nome": "DUVAL ZEZI MONTEIRO",
        "estabelecimento_cnes": "2320053",
        "estabelecimento_nome": "Centro de Saude Cristino Jose da Silva",
        "equipe_ine": "0000015962",
        "ine_master": "0000015962",
        "equipe_nome": "ESF CRISTINO",
        "dt_registro_producao_mais_recente": "2024-07-29"
    },
    {
        "paciente_nome": "ADRILENE CONCEICAO PESSOA",
        "cidadao_cpf_dt_nascimento": "89566185171",
        "id_status_usuario": 14,
        "vencimento_da_coleta": "-",
        "prazo_proxima_coleta": "31/08/2024",
        "idade": 25,
        "id_faixa_etaria": 6,
        "acs_nome": "EDIJANIA CARALI TOLEDO",
        "estabelecimento_cnes": "3068927",
        "estabelecimento_nome": "UBS Diminiz Diniz da Silva",
        "equipe_ine": "0000016004",
        "ine_master": "0000016004",
        "equipe_nome": "ESF DIMINIZ",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADRYELLE LUZ TRAJANO",
        "cidadao_cpf_dt_nascimento": "40941671011",
        "id_status_usuario": 13,
        "vencimento_da_coleta": "-",
        "prazo_proxima_coleta": "31/08/2024",
        "idade": 31,
        "id_faixa_etaria": 6,
        "acs_nome": "JIVALDO APARECIDO GABRIEL",
        "estabelecimento_cnes": "3068927",
        "estabelecimento_nome": "UBS Diminiz Diniz da Silva",
        "equipe_ine": "0000016004",
        "ine_master": "0000016004",
        "equipe_nome": "ESF DIMINIZ",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "ADYLA AZEVEDO BRAGA",
        "cidadao_cpf_dt_nascimento": "95965747946",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "26/08/2025",
        "prazo_proxima_coleta": "Em dia",
        "idade": 62,
        "id_faixa_etaria": 8,
        "acs_nome": "VALDERI CONEICAO FIUZA",
        "estabelecimento_cnes": "2320053",
        "estabelecimento_nome": "Centro de Saude Cristino Jose da Silva",
        "equipe_ine": "0000015962",
        "ine_master": "0000015962",
        "equipe_nome": "ESF CRISTINO",
        "dt_registro_producao_mais_recente": "2024-07-29"
    },
    {
        "paciente_nome": "ADYLA CONCEIÇÃO PINTO",
        "cidadao_cpf_dt_nascimento": "50016067420",
        "id_status_usuario": 13,
        "vencimento_da_coleta": "-",
        "prazo_proxima_coleta": "31/08/2024",
        "idade": 25,
        "id_faixa_etaria": 6,
        "acs_nome": "MARILZA COIS NEPOMUCENO",
        "estabelecimento_cnes": null,
        "estabelecimento_nome": null,
        "equipe_ine": "0",
        "ine_master": "0",
        "equipe_nome": "SEM EQUIPE RESPONSÁVEL",
        "dt_registro_producao_mais_recente": "2024-01-25"
    },
    {
        "paciente_nome": "AGATA CONRADO PONTES",
        "cidadao_cpf_dt_nascimento": "55644381515",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "23/08/2025",
        "prazo_proxima_coleta": "Em dia",
        "idade": 28,
        "id_faixa_etaria": 6,
        "acs_nome": "AGNELO FELDHAUS LIDUARIO",
        "estabelecimento_cnes": "2320029",
        "estabelecimento_nome": "UBS Maria Jandira Vieira Peixoto Sao Francisco",
        "equipe_ine": "0000015954",
        "ine_master": "0000015954",
        "equipe_nome": "ESF SAO FRANCISCO",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
    {
        "paciente_nome": "AGATHA MACHADO VALE",
        "cidadao_cpf_dt_nascimento": "80942299278",
        "id_status_usuario": 12,
        "vencimento_da_coleta": "19/03/2027",
        "prazo_proxima_coleta": "Em dia",
        "idade": 35,
        "id_faixa_etaria": 6,
        "acs_nome": "JESUS RAZZINE TURIBIO",
        "estabelecimento_cnes": "3068927",
        "estabelecimento_nome": "UBS Diminiz Diniz da Silva",
        "equipe_ine": "0000016004",
        "ine_master": "0000016004",
        "equipe_nome": "ESF DIMINIZ",
        "dt_registro_producao_mais_recente": "2024-07-26"
    },
  ]
const selecionar_status_usuario_descricao = ({value})=> {
  const alert = {
    backgroundColor: "#F8BBAE",
    border: "1px solid #EF565D",
    borderRadius: "5px",
    color: "#EF565D",
    padding: "2px",
    fontWeight : 550,
    width : "90%",
    display : "flex",
    gap : "5px",
    alignItems: "center",
    justifyContent : "center",
    padding : "3px 10px"
  }
  const atencao = {
    backgroundColor: "#F4CCAB",
    border: "1px solid #E98633",
    borderRadius: "5px",
    color: "#E98633",
    padding: "2px",
    fontWeight : 550,
    width : "fit-content",
    display : "flex",
    gap : "5px",
    alignItems: "center",
    justifyContent : "center",
    padding : "3px 10px"
  }
  const styleStatus = {
    13 : alert,
    14 : alert,
    15 : atencao,
    16 : alert
  }
  const alertSymbolStyle = {
    border: "2px solid #EF565D",
    borderRadius : "100%",
    width : "18px",
    height : "18px",
    fontSize : "8px",
    fontWeight : "600",
    display : "flex",
    alignItems: "center",
    justifyContent : "center"
  }
  const atencaoSymbolStyle = {
    border: "2px solid #E98633",
    borderRadius : "100%",
    width : "18px",
    height : "18px",
    fontSize : "8px",
    fontWeight : "600",
    display : "flex",
    alignItems: "center",
    justifyContent : "center"
  }

  const descricao = status_usuario_descricao.find(item => item?.id_status_usuario == value)?.status_usuario_descricao
  return <div style={styleStatus[value]}> 
    {[13,14,16].includes(value) &&  <span style={alertSymbolStyle}>✖</span>} 
    {[15].includes(value) &&  <span style={atencaoSymbolStyle}>!</span>} 
    <span>{descricao}</span>
    </div>
}

const prazoStyle = ({value})=>{
  const atencao = {
    backgroundColor: "#F4CCAB",
    border: "1px solid #E98633",
    borderRadius: "5px",
    color: "#E98633",
    padding: "2px",
    fontWeight : 550,
    width : "fit-content",
    display : "flex",
    gap : "5px",
    alignItems: "center",
    justifyContent : "center",
    padding : "3px 10px"
  }
  const atencaoSymbolStyle = {
    border: "2px solid #E98633",
    borderRadius : "100%",
    width : "18px",
    height : "18px",
    fontSize : "8px",
    fontWeight : "600",
    display : "flex",
    alignItems: "center",
    justifyContent : "center"
  }

  return <div style={value != "Em dia" ? atencao : {}}>{value != "Em dia" && <span style={atencaoSymbolStyle}>!</span>} {value}</div>

}

const colunasCito=[
  {
    align: 'left',
    field: 'paciente_nome',
    showOnPrint: true,
    headerAlign: 'center',
    headerName: 'NOME',
    width: 320
  },
  {
    align: 'center',
    field: 'cidadao_cpf_dt_nascimento',
    showOnPrint: true,
    headerAlign: 'center',
    headerName: 'CPF / DATA DE NASCIMENTO',
    width: 140
  },
  {
    align: 'center',
    field: 'id_status_usuario',
    showOnPrint: true,
    headerAlign: 'center',
    headerName: 'STATUS DA COLETA',
    width: 300
  },
  {
    align: 'center',
    field: 'vencimento_da_coleta',
    showOnPrint: true,
    headerAlign: 'center',
    headerName: 'VENCIMENTO DA COLETA',
    width: 100
  },
  {
    align: 'center',
    field: 'prazo_proxima_coleta',
    showOnPrint: true,
    headerAlign: 'center',
    headerName: 'PRAZO PARA PRÓXIMA COLETA',
    width: 130
  },
  {
    align: 'center',
    field: 'idade',
    showOnPrint: true,
    headerAlign: 'center',
    headerName: 'IDADE',
    width: 80
  },
  {
    align: 'center',
    field: 'equipe_nome',
    showOnPrint: true,
    headerAlign: 'center',
    headerName: 'EQUIPE',
    width: 250,
    sortable : false
  },
  {
    align: 'center',
    field: 'acs_nome',
    showOnPrint: true,
    headerAlign: 'center',
    headerName: 'Profissional Responsável',
    width: 250
  }
]
const larguraColunasCito = {
  0 : "250px",
  1 : "80px",
  2 : "280px",
  3 : "50px",
  4 : "100px",
  5 : "80px",
  6 : "120px",
  7 : "120px",
}

const Template = (args) => <TabelaImpressao {...args}/>

export const Citopatologico = Template.bind({});

Citopatologico.args={
  data : dataCito,
  colunas : colunasCito,
  lista : "CITOPATOLOGICO",
  divisorVertical : [1,4],
  largura_colunas_impressao : larguraColunasCito,
  status_usuario_descricao : status_usuario_descricao,
  data_producao_mais_recente : new Date(dataCito.reduce((maisRecente, objeto) => {
    const dataAtual = new Date(objeto.dt_registro_producao_mais_recente);
    const dataMaisRecenteAnterior = new Date(maisRecente);
    return dataAtual > dataMaisRecenteAnterior ? objeto.dt_registro_producao_mais_recente : maisRecente
  }, "2000-01-01")).toLocaleString('pt-BR', { 
    timeZone: 'UTC',
    year: '2-digit',
    month: '2-digit',
    day: '2-digit'
  }),
  listas_auxiliares : {
    status_usuario_descricao
  }
}