export const dataSemDum = [
  {
    "chave_id_gestacao": "40",
    "municipio_id_sus": "111111",
    "equipe_ine": "0000016004",
    "equipe_nome": "ESF MATA ESCURA",
    "cidadao_nome": "MADELAINE SOUZA MEIRELES",
    "cidadao_cpf_dt_nascimento": "76573476412",
    "gestacao_data_dpp": null,
    "gestacao_idade_gestacional_atual": null,
    "gestacao_idade_gestacional_primeiro_atendimento": null,
    "gestacao_quadrimestre": "sem DUM",
    "consulta_prenatal_ultima_data": "2024-07-26",
    "consultas_pre_natal_validas": null,
    "id_atendimento_odontologico": 3,
    "id_exame_hiv_sifilis": 5,
    "id_registro_aborto": 2,
    "id_registro_parto": 2,
    "id_status_usuario": 11,
    "acs_nome": "ACUCENA VIEIRA MELO",
    "atualizacao_data": "2024-07-29",
    "criacao_data": "2024-07-29",
    "municipio_uf": "Demo - Bonfim - RR",
    "dt_registro_producao_mais_recente": "2024-07-26"
  },
  {
    "chave_id_gestacao": "89",
    "municipio_id_sus": "111111",
    "equipe_ine": "0000015962",
    "equipe_nome": "ESF SANTO CRISTO",
    "cidadao_nome": "DAGMAR MENEZES MELO",
    "cidadao_cpf_dt_nascimento": "76589035623",
    "gestacao_data_dpp": null,
    "gestacao_idade_gestacional_atual": null,
    "gestacao_idade_gestacional_primeiro_atendimento": null,
    "gestacao_quadrimestre": "sem DUM",
    "consulta_prenatal_ultima_data": "2024-07-04",
    "consultas_pre_natal_validas": null,
    "id_atendimento_odontologico": 3,
    "id_exame_hiv_sifilis": 5,
    "id_registro_aborto": 2,
    "id_registro_parto": 2,
    "id_status_usuario": 11,
    "acs_nome": "BERNARDO FERREIRA MOTA",
    "atualizacao_data": "2024-07-29",
    "criacao_data": "2024-07-29",
    "municipio_uf": "Demo - Bonfim - RR",
    "dt_registro_producao_mais_recente": "2024-07-25"
  },
  {
    "chave_id_gestacao": "21",
    "municipio_id_sus": "111111",
    "equipe_ine": "0000015989",
    "equipe_nome": "SEM EQUIPE RESPONSÁVEL",
    "cidadao_nome": "ADRIANA MELO FIGUEIRA",
    "cidadao_cpf_dt_nascimento": "67854378954",
    "gestacao_data_dpp": null,
    "gestacao_idade_gestacional_atual": null,
    "gestacao_idade_gestacional_primeiro_atendimento": null,
    "gestacao_quadrimestre": "sem DUM",
    "consulta_prenatal_ultima_data": "2024-03-11",
    "consultas_pre_natal_validas": null,
    "id_atendimento_odontologico": 3,
    "id_exame_hiv_sifilis": 5,
    "id_registro_aborto": 2,
    "id_registro_parto": 2,
    "id_status_usuario": 11,
    "acs_nome": "MARCOS FONSECA MELO",
    "atualizacao_data": "2024-07-29",
    "criacao_data": "2024-07-29",
    "municipio_uf": "Demo - Bonfim - RR",
    "dt_registro_producao_mais_recente": "2024-07-23"
  },
  {
    "chave_id_gestacao": "51",
    "municipio_id_sus": "111111",
    "equipe_ine": "0",
    "equipe_nome": "SEM EQUIPE RESPONSÁVEL",
    "cidadao_nome": "CARMEM LUCIA MADEIRA",
    "cidadao_cpf_dt_nascimento": "67854378954",
    "gestacao_data_dpp": null,
    "gestacao_idade_gestacional_atual": null,
    "gestacao_idade_gestacional_primeiro_atendimento": null,
    "gestacao_quadrimestre": "sem DUM",
    "consulta_prenatal_ultima_data": "2024-03-23",
    "consultas_pre_natal_validas": null,
    "id_atendimento_odontologico": 3,
    "id_exame_hiv_sifilis": 5,
    "id_registro_aborto": 2,
    "id_registro_parto": 2,
    "id_status_usuario": 11,
    "acs_nome": "JOAO MARCIUS MELEN",
    "atualizacao_data": "2024-07-29",
    "criacao_data": "2024-07-29",
    "municipio_uf": "Demo - Bonfim - RR",
    "dt_registro_producao_mais_recente": "2024-03-23"
  },
  {
    "chave_id_gestacao": "00",
    "municipio_id_sus": "111111",
    "equipe_ine": "0000015962",
    "equipe_nome": "ESF SANTO CRISTO",
    "cidadao_nome": "CAMILA DO CARMO SOUZA",
    "cidadao_cpf_dt_nascimento": "65478934612",
    "gestacao_data_dpp": null,
    "gestacao_idade_gestacional_atual": null,
    "gestacao_idade_gestacional_primeiro_atendimento": null,
    "gestacao_quadrimestre": "sem DUM",
    "consulta_prenatal_ultima_data": "2024-07-16",
    "consultas_pre_natal_validas": null,
    "id_atendimento_odontologico": 3,
    "id_exame_hiv_sifilis": 5,
    "id_registro_aborto": 2,
    "id_registro_parto": 2,
    "id_status_usuario": 11,
    "acs_nome": "BERNARDO FERREIRA MOTA",
    "atualizacao_data": "2024-07-29",
    "criacao_data": "2024-07-29",
    "municipio_uf": "Demo - Bonfim - RR",
    "dt_registro_producao_mais_recente": "2024-07-25"
  },
  {
    "chave_id_gestacao": "55",
    "municipio_id_sus": "111111",
    "equipe_ine": "0000016004",
    "equipe_nome": "ESF MATA ESCURA",
    "cidadao_nome": "LAURA VIANA MOTA",
    "cidadao_cpf_dt_nascimento": "67945376123",
    "gestacao_data_dpp": null,
    "gestacao_idade_gestacional_atual": null,
    "gestacao_idade_gestacional_primeiro_atendimento": null,
    "gestacao_quadrimestre": "sem DUM",
    "consulta_prenatal_ultima_data": "2024-07-26",
    "consultas_pre_natal_validas": null,
    "id_atendimento_odontologico": 3,
    "id_exame_hiv_sifilis": 5,
    "id_registro_aborto": 2,
    "id_registro_parto": 2,
    "id_status_usuario": 11,
    "acs_nome": "ACUCENA VIEIRA MELO",
    "atualizacao_data": "2024-07-29",
    "criacao_data": "2024-07-29",
    "municipio_uf": "Demo - Bonfim - RR",
    "dt_registro_producao_mais_recente": "2024-07-26"
  },
  {
    "chave_id_gestacao": "15",
    "municipio_id_sus": "111111",
    "equipe_ine": "0000015962",
    "equipe_nome": "ESF SANTO CRISTO",
    "cidadao_nome": "FIRMINA DA CRUZ CABRALIA",
    "cidadao_cpf_dt_nascimento": "65478034698",
    "gestacao_data_dpp": null,
    "gestacao_idade_gestacional_atual": null,
    "gestacao_idade_gestacional_primeiro_atendimento": null,
    "gestacao_quadrimestre": "sem DUM",
    "consulta_prenatal_ultima_data": "2024-07-25",
    "consultas_pre_natal_validas": null,
    "id_atendimento_odontologico": 3,
    "id_exame_hiv_sifilis": 5,
    "id_registro_aborto": 2,
    "id_registro_parto": 2,
    "id_status_usuario": 11,
    "acs_nome": "VANNDA GOMES DA COSTA",
    "atualizacao_data": "2024-07-29",
    "criacao_data": "2024-07-29",
    "municipio_uf": "Demo - Bonfim - RR",
    "dt_registro_producao_mais_recente": "2024-07-25"
  },
  {
    "chave_id_gestacao": "73",
    "municipio_id_sus": "111111",
    "equipe_ine": "0000016004",
    "equipe_nome": "ESF MATA ESCURA",
    "cidadao_nome": "OLINDA GOMES FARIAS",
    "cidadao_cpf_dt_nascimento": "67534587634",
    "gestacao_data_dpp": null,
    "gestacao_idade_gestacional_atual": null,
    "gestacao_idade_gestacional_primeiro_atendimento": null,
    "gestacao_quadrimestre": "sem DUM",
    "consulta_prenatal_ultima_data": "2024-07-25",
    "consultas_pre_natal_validas": null,
    "id_atendimento_odontologico": 3,
    "id_exame_hiv_sifilis": 5,
    "id_registro_aborto": 2,
    "id_registro_parto": 2,
    "id_status_usuario": 11,
    "acs_nome": "CARLA MEDEIROS BASTOS",
    "atualizacao_data": "2024-07-29",
    "criacao_data": "2024-07-29",
    "municipio_uf": "Demo - Bonfim - RR",
    "dt_registro_producao_mais_recente": "2024-07-26"
  },
];
