export const dataHipertensao=[
    {
        "cidadao_nome": "DAVIDSON MUSTAFA ZEHED",
        "cidadao_cpf": "32702133878",
        "identificacao_condicao_hipertensao": "Autorreferida",
        "dt_consulta_mais_recente": "2020-09-23",
        "prazo_proxima_consulta": "Até 31/Agosto",
        "dt_afericao_pressao_mais_recente": null,
        "prazo_proxima_afericao_pa": "Até 31/Agosto",
        "acs_nome_cadastro": "Fernanda Soares Ferreira",
        "equipe_ine_cadastro": "0001540971",
        "equipe_nome_cadastro": "ESF GOIANA"
    },
    {
        "cidadao_nome": "JOSE GALDINO ALVES DA PAZ",
        "cidadao_cpf": "33343316873",
        "identificacao_condicao_hipertensao": "Diagnóstico Clínico",
        "dt_consulta_mais_recente": "2023-05-11",
        "prazo_proxima_consulta": "Em dia",
        "dt_afericao_pressao_mais_recente": "2023-05-11",
        "prazo_proxima_afericao_pa": "Em dia",
        "acs_nome_cadastro": "Fabiana Matias de Oliveira",
        "equipe_ine_cadastro": "0001540971",
        "equipe_nome_cadastro": "ESF GOIANA"
    },
    {
        "cidadao_nome": "ACSA DOS SANTOS LOPES",
        "cidadao_cpf": "32704359830",
        "identificacao_condicao_hipertensao": "Diagnóstico Clínico",
        "dt_consulta_mais_recente": "2023-05-12",
        "prazo_proxima_consulta": "Até 31/Agosto",
        "dt_afericao_pressao_mais_recente": null,
        "prazo_proxima_afericao_pa": "Até 31/Agosto",
        "acs_nome_cadastro": "Thais Jensen",
        "equipe_ine_cadastro": "0001540971",
        "equipe_nome_cadastro": "ESF GOIANA"
    },
    {
        "cidadao_nome": "ANA PAULA DA SILVA SOARES",
        "cidadao_cpf": "41364717859",
        "identificacao_condicao_hipertensao": "Autorreferida",
        "dt_consulta_mais_recente": "2022-11-23",
        "prazo_proxima_consulta": "Até 31/Agosto",
        "dt_afericao_pressao_mais_recente": null,
        "prazo_proxima_afericao_pa": "Até 31/Agosto",
        "acs_nome_cadastro": "Fernanda Soares Ferreira",
        "equipe_ine_cadastro": "0001540971",
        "equipe_nome_cadastro": "ESF GOIANA"
    },
    {
        "cidadao_nome": "APARECIDA VANESSA DO AMARAL",
        "cidadao_cpf": "35299537840",
        "identificacao_condicao_hipertensao": "Diagnóstico Clínico",
        "dt_consulta_mais_recente": "2023-05-26",
        "prazo_proxima_consulta": "Até 31/Agosto",
        "dt_afericao_pressao_mais_recente": null,
        "prazo_proxima_afericao_pa": "Até 31/Agosto",
        "acs_nome_cadastro": "Marco Alberto Costa Santi",
        "equipe_ine_cadastro": "0001540971",
        "equipe_nome_cadastro": "ESF GOIANA"
    },
    {
        "cidadao_nome": "CLAUDINEI DO ROSARIO",
        "cidadao_cpf": "34353421883",
        "identificacao_condicao_hipertensao": "Diagnóstico Clínico",
        "dt_consulta_mais_recente": "2015-07-24",
        "prazo_proxima_consulta": "Até 31/Agosto",
        "dt_afericao_pressao_mais_recente": null,
        "prazo_proxima_afericao_pa": "Até 31/Agosto",
        "acs_nome_cadastro": "Marco Alberto Costa Santi",
        "equipe_ine_cadastro": "0001540971",
        "equipe_nome_cadastro": "ESF GOIANA"
    },
    {
        "cidadao_nome": "CRISTIANE DELGADO SEMO",
        "cidadao_cpf": "42402357827",
        "identificacao_condicao_hipertensao": "Autorreferida",
        "dt_consulta_mais_recente": "2019-02-05",
        "prazo_proxima_consulta": "Até 31/Agosto",
        "dt_afericao_pressao_mais_recente": null,
        "prazo_proxima_afericao_pa": "Até 31/Agosto",
        "acs_nome_cadastro": "Fernanda Soares Ferreira",
        "equipe_ine_cadastro": "0001540971",
        "equipe_nome_cadastro": "ESF GOIANA"
    },
    {
        "cidadao_nome": "DEBORA CAROLINA SOUZA",
        "cidadao_cpf": "22910043878",
        "identificacao_condicao_hipertensao": "Diagnóstico Clínico",
        "dt_consulta_mais_recente": "2023-05-22",
        "prazo_proxima_consulta": "Em dia",
        "dt_afericao_pressao_mais_recente": "2023-05-22",
        "prazo_proxima_afericao_pa": "Em dia",
        "acs_nome_cadastro": "Marco Alberto Costa Santi",
        "equipe_ine_cadastro": "0001540971",
        "equipe_nome_cadastro": "ESF GOIANA"
    },
    {
        "cidadao_nome": "FAUSTINO DA COSTA JUNIOR",
        "cidadao_cpf": "34445553859",
        "identificacao_condicao_hipertensao": "Diagnóstico Clínico",
        "dt_consulta_mais_recente": "2022-12-19",
        "prazo_proxima_consulta": "Até 31/Agosto",
        "dt_afericao_pressao_mais_recente": null,
        "prazo_proxima_afericao_pa": "Até 31/Agosto",
        "acs_nome_cadastro": "Fernanda Soares Ferreira",
        "equipe_ine_cadastro": "0001540971",
        "equipe_nome_cadastro": "ESF GOIANA"
    },
    {
        "cidadao_nome": "FRANCIELE DE DEUS BOA VENTURA",
        "cidadao_cpf": "43656184828",
        "identificacao_condicao_hipertensao": "Diagnóstico Clínico",
        "dt_consulta_mais_recente": "2020-10-19",
        "prazo_proxima_consulta": "Até 31/Agosto",
        "dt_afericao_pressao_mais_recente": null,
        "prazo_proxima_afericao_pa": "Até 31/Agosto",
        "acs_nome_cadastro": "Raquel Nascimento da Silva",
        "equipe_ine_cadastro": "0001540971",
        "equipe_nome_cadastro": "ESF GOIANA"
    },
    {
        "cidadao_nome": "GABRIEL DE ALMEIDA FERNANDES",
        "cidadao_cpf": "44455263802",
        "identificacao_condicao_hipertensao": "Diagnostico Clinico",
        "dt_consulta_mais_recente": "2022-09-27",
        "prazo_proxima_consulta": "Até 31/Agosto",
        "dt_afericao_pressao_mais_recente": null,
        "prazo_proxima_afericao_pa": "Até 31/Agosto",
        "acs_nome_cadastro": "Fernanda Soares Ferreira",
        "equipe_ine_cadastro": "0001540971",
        "equipe_nome_cadastro": "ESF GOIANA"
    },
  ]
  